- avro-migration-helper/src/main/java/com/linkedin/avro/compatibility/AvroCompatibilityHelper.java
- avro-migration-helper/src/main/java/org/apache/avro/io/AbstractAvroAdapter.java
- avro-migration-helper/src/main/java/org/apache/avro/io/Avro14Adapter.java
- avro-migration-helper/src/main/java/org/apache/avro/io/Avro17Adapter.java
- avro-migration-helper/src/main/java/org/apache/avro/io/AvroAdapter.java
- avro-migration-helper/src/test/java/com/linkedin/avro/compatibility/AvroCompatibilityHelperTest.java
Add the following APIs to `AvroCompatibilityHelper`:
- `newInstance(Class, Schema)`:    Instantiates objects of a specific type 
- `getSchema(Type)`: 		  	   Locates the Avro schema associated with a Java (SpecificRecord) type
- `getDefaultValue(Schema.Field)`: Retrieves the default value of an Avro field, if any
> Add new APIs to AvroCompatibilityHelper

- avro-fastserde/gettingstarted.md
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorBase.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGeneratorBase.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/PrimitiveFloatList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/Utils.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastSerdeCacheTest.java
When application is using play framework with hot-reload enabled, fast-avro
couldn't find the right classpath by extracting from system property:java.class.path.
So this code change will explicitly find all the classes being used in the
generated files and put the corresponding libraries in the compile classpath.
Play framework is using both current classloader and the thread context classloader
to discover class path in hot reload feature. In fast-avro class generation/compilation,
we have to do the same time to align with this behavior.
Once the generated file is compiled successfully, loading the compiled classes
is not a problem in play framework with hot-reload enabled.
> Dynamically infer classpath by classloader according to the class usage

- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/micro/benchmark/AvroGenericSerializer.java
- avro-migration-helper/src/main/java/com/linkedin/avro/compatibility/AvroCompatibilityHelper.java
- avro-migration-helper/src/main/java/org/apache/avro/io/Avro14Adapter.java
- avro-migration-helper/src/main/java/org/apache/avro/io/Avro17Adapter.java
- avro-migration-helper/src/main/java/org/apache/avro/io/AvroAdapter.java
- avro-migration-helper/src/main/java/org/apache/avro/io/avro18/Avro18BinaryData.java
- avro-migration-helper/src/main/java/org/apache/avro/io/avro18/Avro18BinaryEncoder.java
- avro-migration-helper/src/main/java/org/apache/avro/io/avro18/Avro18BufferedBinaryEncoder.java
- avro-migration-helper/src/main/java/org/apache/avro/io/avro18/Avro18Encoder.java
In Avro-1.7 and above, the default BinaryEncoder implementation is buffered,
which has improved the serialization greatly, but this optimization is
absent in Avro-1.4.
To improve the serialization performance in Avro-1.4, this code change back-ports
the buffered binary encoder implementation from Avro-1.8 to be used
in Avro-1.4.
By running the test: SerDeMicroBenchmark#testFastAvroSerialization with Avro-1.4,
the performance is improved by more than 40% with the new buffered binary encoder (5ms vs 9ms).
With the buffered binary encoder, the fast serialization performance across
all the Avro versions are very similar now.
This code change doesn't change the signature of AvroCompatibilityHelper#newBinaryEncoder,
since we would like to keep it backward compatible, instead it adds a new …
> Added a new method to return buffered binary encoder

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDatumWriterTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorForReuseTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastGenericSerializerGeneratorTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastSerdeTestsSupport.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastSpecificSerializerGeneratorTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastStringableTest.java
This code change optimizes the way how to retrieve back the enum
schema for avro-1.4, so that it doesn't need to parse a enum schema
for every deserialization.
Snippet of generated fast serializer:
private Map<Long, Schema> enumSchemaMap = new ConcurrentHashMap<Long, Schema>();
...
public void serializetestRecord0(IndexedRecord data, Encoder encoder)
throws IOException
{
Schema testEnumEnumSchema1;
if (!enumSchemaMap.containsKey(-3346156575824446940L)) {
testEnumEnumSchema1 = Schema.parse("{\"type\":\"enum\",\"name\":\"testEnum\",\"namespace\":\"com.adpilot.utils.generated.avro\",\"symbols\":[\"A\",\"B\"]}");
enumSchemaMap.put(-3346156575824446940L, testEnumEnumSchema1);
} else {
testEnumEnumSchema1 = enumSchemaMap.get(-3346156575824446940L);
}
...
@FelixGV @radai-rosenblatt
> Updated fast serializer generator to optimize the enum schema generation

- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/backports/Avro17DefaultValuesCache.java
- helper/tests/helper-tests-allavro/build.gradle
Schema.Parser.setValidateDefaults(), SpecificData.getDefaultValue() and GenericData.getDefaultValue() were all added to 1.7 after 1.7.0.
This code mainly provides alternative implementations for these if they are not found (meaning we are running under older 1.7). The alternative implementations are the same we use under avro 1.6.
Under older 1.7 a warning is printed to log once (since presumably upgrading to latest 1.7 should be an easy operation for users)
Also fixed the return value of parse() under avro < 1.7 to correctly reflect the configuration used for parsing.
> add support for old(er) versions of avro 1.7

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumReader.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumWriter.java
Previous log level in FastGenericDatumReader/Writer was "info" which affected performance greatly when trying to reuse cached fastDeserializer/Serializer in FastSerdeCache.
By removing log, we can take better advantage of cached fastDeserializer/Serializer.
According one of the JMH benchmark results:
Fast-deserialization latency can be improved from **1.1 ms** to **0.5ms** by this change.
@gaojieliu @FelixGV
> Change log level to debug in FastDatumReader/Writer to improve perf

- avro-fastserde/build.gradle
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastAvroConcurrentHashMap.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDatumReaderWriterUtil.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDatumReaderWriterUtilTest.java
FastDatumReaderWriterUtil is a wrapper utility to create Fast Datum Reader and Writer objects . The Utility internally takes care caching the created objects in order to avoid creation of objects from the same Schema / Schema pair . 
This will help address the inefficiency with Schema#hashCode computation in Avro 1.4 
Pre-requisite to use this util:
1. Schema object will not be changed on-the-FLY, or the changes do NOT require new DatumReader/Writer
2. Your application will always use the same Schema object for the same schema
Latency improvement by caching : 
Comparing with creating new Datum reader / write object for every record 
Deser : ~40% 
Ser  : ~20%
@volauvent @FelixGV @radai-rosenblatt @gaojieliu
> Fast Datum Reader/Writer Util with WeakIdentityHashMap

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/CompositeByteBuffer.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/PrimitiveFloatList.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDeserializerDefaultsTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorForReuseTest.java
Improving the deserialization performance of PrimitiveFloatList. 
1. Using ByteBuffer instead of byte[] . ByeBuffer#getFloat has faster performance than avro readFloat.
2. I am moving the deserialization to array access time only, so that clients can deserialize the records extremely fast. The full deserialization happens only when client tries to access array element. Also cache the deserialized elements into the float array after the first access so later accesses will not see any impact.
Regular fast-avro performance of 1M records of 10kb sized float array:  ~18s
Using the lazy deserialization using ByteBuffer: ~ 2s
> Performance improvement of PrimitiveFloatList by lazy deserialization

- avro-fastserde/build.gradle
- avro-fastserde/regenerate_avro.sh
- avro-fastserde/src/jmh/java/com/linkedin/avro/fastserde/BenchmarkConstants.java
- avro-fastserde/src/jmh/java/com/linkedin/avro/fastserde/FastAvroSerdesBenchmark.java
- avro-fastserde/src/jmh/java/com/linkedin/avro/fastserde/generator/AvroRandomDataGenerator.java
- avro-fastserde/src/jmh/java/com/linkedin/avro/fastserde/generator/GenericRecordBuilder.java
- avro-fastserde/src/jmh/java/com/linkedin/avro/fastserde/generator/RecordBuilder.java
- avro-fastserde/src/jmh/java/com/linkedin/avro/fastserde/generator/RecordBuilderBase.java
- avro-fastserde/src/test/avro/benchmarkSchema.avsc
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/micro/benchmark/AvroGenericSerializer.java
Use JMH suite benchmark performance of vanilla avro and fast-serde serialization and deserialization. It ueses AvroRandomDataGenerator to generate avro data according to specified Schema.
To run this benchmark: `./gradlew :avro-fastserde:jmh -PUSE_AVRO_14/17/18`
Then it will benchmark the average serdes latency and print GC details of vanilla Avro and fast-serdes.
You also can test your own AVRO schema by replacing the schema in
`avro-util/avro-fastserde/src/test/avro/benchmarkSchema.avsc`
JMH benchmark is very helpful for -
1. Benchmark the serdes latency reduction of customer schema brought by applying avro-fastserde
2. Investigate in the performance improvement and bottleneck of different schema pattern and avro version
@gaojieliu @FelixGV
> JMH benchmark suite for avro-fastserde

- avro-fastserde/build.gradle
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDatumReaderWriterUtil.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/WeakIdentityHashMap.java
Removed jboss.util.collection.WeakIdentityHashMap to meet LinkedIn Open Source Licenses requirement.
Re-run the JMH benchmark with the new WeakIdentityHashMap in Avro 1.4. Compared with creating Datum Reader/Writer for each record, latency reduction by using FastDatumReaderWriterUtil  -
> Deserialization : ~50%, from 2.4ms to 1.2ms;
> Serialization : ~20%, from 3.4ms to 2.6ms;
The performance improvement is the same as #37 
@FelixGV @gaojieliu @radai-rosenblatt @pravk03
> Implement WeakIdentityHashMap in avro-fastserde

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/CompositeByteBuffer.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/PrimitiveFloatList.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDeserializerDefaultsTest.java
Setup composite byte buffer even for general non-avro List<Float> interface implementation of PrimitiveFloatList usage.
eg
PrimitiveFloatList list = new PrimitiveFloatList(10);
The above use-case will not use the ByteBuffer data buffer, but cacheFromByteBuffer tries to read from the ByteBuffer to fill in float array, which would fail if it is not initialized.
> Initialize ByteBuffer for PrimitiveFloatList List<Float> interface usage

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastGenericSerializerGeneratorTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/SchemaAssistantTest.java
Previously, the code is checking schema type to decide the right index,
and this change was introduced to accommodate Avro-1.4, but this is
not appropriate since Union could contain multiple record types, which
will cause the writen index will always be the index of the first record.
The fix is to check the full name of the schema instead of type name.
@volauvent @FelixGV
> Fixed a bug in processUnion of FastSerializer

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
Fixed two bugs which caused FastDeserializer generation failure -
1. Fixed null exception when updating actual exceptions for already generated record method
2. Corrected iteration order of value action symbols for nested Map field
@gaojieliu @FelixGV @radai-rosenblatt @pravk03
> Fixed two bugs in FastDeserializerGenerator

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/CompositeByteBuffer.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorForReuseTest.java
The buffer size should be less than equal to the new size for object reuse to utilize the existing buffer in CompositeByteBuffer. The bug did not check for equality.
> Fix a bug in object reuse in CompositeByteBuffer

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
Improved fast deserialization speed by avoiding current field schema retrieval cost.
Changed to use fields' schema directly instead of registering and then retrieving
them from HashMap.
JMH benchmark results of fast-deserialization time
1. Enum array with 200 elements
```
|   Avro 1.4(ns)   |  Avro 1.8(ns)
Before  |   7452           |   13101 
After   |   5374           |   7858 
```
2. Record array with 200 elements
```
|   Avro 1.4(ns)   |   Avro 1.8(ns)
Before  |   23068          |   24519
After   |   17854          |   18549
```
@gaojieliu @FelixGV @radai-rosenblatt
> Improve fast deserialization by avoiding field schema retrieval cost

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/org/apache/avro/io/Avro14BinaryDecoderAccessUtil.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/org/apache/avro/io/Avro15BinaryDecoderAccessUtil.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/org/apache/avro/io/Avro16BinaryDecoderAccessUtil.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/org/apache/avro/io/Avro17BinaryDecoderAccessUtil.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-18/src/main/java/org/apache/avro/io/Avro18BinaryDecoderAccessUtil.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/impls/helper-impl-19/src/main/java/org/apache/avro/io/Avro19BinaryDecoderAccessUtil.java
Venice has a local optimization requires re-initialize a BinaryDecoder, but the method signature is different in avro 1.4 and versions after 1.4. In order to be compatible with all avro versions, we need to add this method in AvroCompatibilityHelper. Created several classes of AvroXXBinaryDecoderConfigurer since init/configure method in BinaryDecoder is package-private.
> add newBinaryDecoder which re-configures a BinaryDecoder in AvroCompatibilityHelper

- avro-fastserde/src/main/java/com/linkedin/avro/api/PrimitiveFloatList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/ByteBufferBackedPrimitiveFloatList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/coldstart/ColdPrimitiveFloatList.java
- avro-fastserde/src/main/java/org/apache/avro/generic/ColdDatumReaderMixIn.java
- avro-fastserde/src/main/java/org/apache/avro/generic/ColdGenericDatumReader.java
- avro-fastserde/src/main/java/org/apache/avro/generic/ColdSpecificDatumReader.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDeserializerDefaultsTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
The PrimitiveFloatList is an API which users should expect to rely on,
so it is wrong to degrade to the more constrained List<Float> API while
Fast-Avro is still cold. This commit introduces several changes to make
the extended API reliably present whenever using Fast-Avro, regardless
of being cold or warm.
- Changed PrimitiveFloatList to an interface, in a new package called:
com.linkedin.avro.api; since the package name migration makes this an
incompatible change, it would be desirable for the next release to
not increment only the patch version. Having a proper package name
for API extension should make things cleaner in the future as we add
other optimized APIs (e.g. PR #45).
- Renamed the old class to ByteBufferBackedPrimitiveFloatList, and made
it implement the new interface.
- …
> Always return PrimitiveFloatList, even when cold

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/Array_of_UNION_GenericSerializer_585074122056792963.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/Array_of_record_GenericSerializer_1629046702287533603.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWriteEnum_GenericSerializer_6137374763587019173.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWriteFixed_GenericSerializer_8889056593487745201.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWriteMultipleChoiceUnion_GenericSerializer_4388851848367235159.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWritePrimitives_GenericSerializer_5300080091170871849.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWriteRightUnionIndex_GenericSerializer_5485438821003579903.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWriteSubRecordCollectionsField_GenericSerializer_4869519538077502381.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWriteSubRecordComplexCollectionsField_GenericSerializer_6532465341493029871.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastGenericSerializerGeneratorTest_shouldWriteSubRecordField_GenericSerializer_1161833140095035747.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/Map_of_UNION_GenericSerializer_2087096002965517991.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/Map_of_record_GenericSerializer_2141121767969292399.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
Improved fast serialization speed by avoiding the cost of storing and retrieving Enum schemas
in a Hashmap in Avro 1.4. We have seen ~44% improvement of serialization latency for Enum array.
This PR helps to resolve issue #50 
JMH benchmark results of fast serialization time of an 200 elements EnumArray under Avro 1.4
**Before** 
```
FastAvroSerdesBenchmark.testFastAvroSerialization                                   avgt   10  12054.915 ± 1852.177   ns/op
FastAvroSerdesBenchmark.testFastAvroSerialization:·gc.alloc.rate                    avgt   10    255.063 ±   42.062  MB/sec
FastAvroSerdesBenchmark.testFastAvroSerialization:·gc.alloc.rate.norm               avgt   10   3352.001 ±    0.001    B/op
FastAvroSerdesBenchmark.testFastAvroSerialization:·gc.churn.PS_Eden_Space           avgt …
```
> Improved fast serializer code generation logic for Enum type

- avro-fastserde/build.gradle
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Array_of_BOOLEAN_GenericDeserializer_5988037297456147388_5988037297456147388.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Array_of_DOUBLE_GenericDeserializer_6064316435611861740_6064316435611861740.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Array_of_INT_GenericDeserializer_3343716480540445685_3343716480540445685.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Array_of_LONG_GenericDeserializer_2055015354772118358_2055015354772118358.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/FastGenericDeserializerGeneratorTest_shouldReadNestedMap_GenericDeserializer_8750596110605641040_8750596110605641040.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Array_of_BOOLEAN_GenericDeserializer_5988037297456147388_5988037297456147388.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Array_of_DOUBLE_GenericDeserializer_6064316435611861740_6064316435611861740.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Array_of_INT_GenericDeserializer_3343716480540445685_3343716480540445685.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Array_of_LONG_GenericDeserializer_2055015354772118358_2055015354772118358.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/FastGenericDeserializerGeneratorTest_shouldReadNestedMap_GenericDeserializer_3649952671819772385_3649952671819772385.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Array_of_BOOLEAN_GenericDeserializer_5988037297456147388_5988037297456147388.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Array_of_DOUBLE_GenericDeserializer_6064316435611861740_6064316435611861740.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Array_of_INT_GenericDeserializer_3343716480540445685_3343716480540445685.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Array_of_LONG_GenericDeserializer_2055015354772118358_2055015354772118358.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/FastGenericDeserializerGeneratorTest_shouldReadNestedMap_GenericDeserializer_3649952671819772385_3649952671819772385.java
- avro-fastserde/src/jmh/java/com/linkedin/avro/fastserde/FastAvroSerdesBenchmark.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveBooleanArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveDoubleArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveFloatArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveIntArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveLongArrayList.java
- avro-fastserde/src/test/avro/benchmarkSchema.avsc
On the double array use case, memory allocation of deserialization goes from
288 B/op to 48 B/op. There are more optimized implementations that should be
possible for some of the types.
> Array-based implementation of the PrimitiveList APIs

- avro-fastserde/build.gradle
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumReader.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumWriter.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeBase.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
* slf4j APIs are used now in place of log4j APIs
* slf4j-log4j12 binding dropped from dependencies
> slf4j logging API support in fast-avro (#67)

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeBase.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
* schema content is not logged upon successful fast(de)serializer compilation by default
* success messages are logged after actual (de)serializer generation in FastSerdeCache
> logger verbosity changes

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Array_of_TestRecord_SpecificDeserializer_6709200327098145888_6709200327098145888.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Array_of_UNION_SpecificDeserializer_735161557101031552_735161557101031552.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/ClasspathTestRecord_SpecificDeserializer_4580844570251215039_2703298965059642600.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Map_of_TestRecord_SpecificDeserializer_3436583053015536530_3436583053015536530.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/Map_of_UNION_SpecificDeserializer_1942337358604109790_1942337358604109790.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/TestRecord_SpecificDeserializer_4584175291925934544_4584175291925934544.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/TestRecord_SpecificDeserializer_6151968197633927516_4584175291925934544.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Array_of_TestRecord_SpecificDeserializer_6709200327098145888_6709200327098145888.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Array_of_UNION_SpecificDeserializer_735161557101031552_735161557101031552.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/ClasspathTestRecord_SpecificDeserializer_4580844570251215039_2703298965059642600.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Map_of_TestRecord_SpecificDeserializer_3436583053015536530_3436583053015536530.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/Map_of_UNION_SpecificDeserializer_1942337358604109790_1942337358604109790.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/TestRecord_SpecificDeserializer_4584175291925934544_4584175291925934544.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/TestRecord_SpecificDeserializer_6151968197633927516_4584175291925934544.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Array_of_TestRecord_SpecificDeserializer_6709200327098145888_6709200327098145888.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Array_of_UNION_SpecificDeserializer_735161557101031552_735161557101031552.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/ClasspathTestRecord_SpecificDeserializer_4580844570251215039_2703298965059642600.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Map_of_TestRecord_SpecificDeserializer_3436583053015536530_3436583053015536530.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/Map_of_UNION_SpecificDeserializer_1942337358604109790_1942337358604109790.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/TestRecord_SpecificDeserializer_4584175291925934544_4584175291925934544.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/TestRecord_SpecificDeserializer_6151968197633927516_4584175291925934544.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/test/avro/classPathTest.avsc
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastSpecificDeserializerGeneratorTest.java
- avro-fastserde/src/test/resources/schema/classpathOldTest.avsc
The known type names held by SchemaAssistant.fullyQualifiedClassNameSet also included names for types that had been removed within reader schema. This led to ClassNotFoundException in com.linkedin.avro.fastserde.Utils#inferCompileDependencies method during generation of deserializer for specific record.
This fix adds an additional flag to SchemaAssistant type resolution methods, which allow to omit the inclusion of type name depending on the context.
> Fix for ClassNotFoundException occurring during deserializer compilation classpath inference for specific records.

- .github/workflows/push.yaml
- helper/tests/codegen-14/build.gradle
- helper/tests/codegen-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Generate14TestResources.java
- helper/tests/codegen-14/src/main/raw-avro/by14/RecordWithUnion.avsc
- helper/tests/codegen-15/build.gradle
- helper/tests/codegen-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Generate15TestResources.java
- helper/tests/codegen-15/src/main/raw-avro/by15/RecordWithUnion.avsc
- helper/tests/codegenClasspath/log4j2.xml
- helper/tests/helper-tests-14/src/test/java/com/linkedin/avroutil1/compatibility/avro14/Avro14WireFormatCompatibilityTest.java
- helper/tests/helper-tests-15/src/test/java/com/linkedin/avroutil1/compatibility/avro15/Avro15WireFormatCompatibilityTest.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroWireFormatCompatibilityTest.java
- helper/tests/helper-tests-common/src/main/java/com/linkedin/avroutil1/TestUtil.java
codegen-X modules in helper tests now can generate not just specific record classes from schemas, but also payloads (serialized records) of those generated records in json and binary wire formats.
added tests that show that avro 1.4 and 1.5 disagree on json format while all avro can read binaries produced by 1.4 and 1.5 - for a single simple schema with an inner record union
> add serialized payload generation, demonstrate avro json format union incompatibility

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
Make isSpecificRecord public in AvroCompatibilityHelper for use.
> Make isSpecificRecord public in AvroCompatibilityHelper

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
if any static initialization blocks called from here throw an exception, that exception would be wrapped into a java.lang.ExceptionInInitializerError, which is not an exception, and will be missed.
this leads to user issues that are harder to figure out since the full caused-by chain is broken
> catch throwable in helper static initialization

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
capture all the way to the whitespace between methods otherwise this matches the middle of a deeply nested condition for a large-enough schema
> fix end-of-custom-coders code block detection

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/FieldBuilder.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson1Utils.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/FieldBuilder14.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/FieldBuilder15.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/FieldBuilder16.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/FieldBuilder17.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/FieldBuilder18.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/FieldBuilder19.java
- helper/tests/helper-tests-110/src/test/java/com/linkedin/avroutil1/compatibility/avro110/AvroCompatibilityHelperAvro110Test.java
- helper/tests/helper-tests-14/src/test/java/com/linkedin/avroutil1/compatibility/avro14/AvroCompatibilityHelperAvro14Test.java
- helper/tests/helper-tests-15/src/test/java/com/linkedin/avroutil1/compatibility/avro15/AvroCompatibilityHelperAvro15Test.java
- helper/tests/helper-tests-16/src/test/java/com/linkedin/avroutil1/compatibility/avro16/AvroCompatibilityHelperAvro16Test.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/AvroCompatibilityHelperAvro17Test.java
- helper/tests/helper-tests-18/src/test/java/com/linkedin/avroutil1/compatibility/avro18/AvroCompatibilityHelperAvro18Test.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/AvroCompatibilityHelperAvro19Test.java
- helper/tests/helper-tests-common/src/main/resources/RecordWithRecursiveTypesAndDefaults.avsc
Before avro 1.9, the default value in **Schema.Field** constructor takes in **JsonNode** object. Since avro 1.9, it starts taking **Object** as its default value. 
This PR adds a helper function **createSchemaField** in **AvroCompatibilityHelper** to create a Schema.Field instance for all avro versions with the help of FieldBuilder interface.
> Add Schema.Field default value compatibility support in avro 1.4-1.10

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/tests/codegen-110/build.gradle
- helper/tests/codegen-110/src/main/compat-avro-w-builders/under110wbuilders/SimpleRecord.avsc
- helper/tests/codegen-18/build.gradle
- helper/tests/codegen-18/src/main/compat-avro-w-builders/under18wbuilders/SimpleRecord.avsc
- helper/tests/codegen-19/build.gradle
- helper/tests/codegen-19/src/main/compat-avro-w-builders/under19wbuilders/SimpleRecord.avsc
- helper/tests/helper-tests-110/src/test/java/com/linkedin/avroutil1/compatibility/avro110/Avro110BuildersTest.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/Avro17BuildersTest.java
- helper/tests/helper-tests-18/src/test/java/com/linkedin/avroutil1/compatibility/avro18/Avro18BuildersTest.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/Avro19BuildersTest.java
addresses #151
this code replaces this bit:
```java
catch (org.apache.avro.AvroMissingFieldException e) {
throw e;
} catch (java.lang.Exception e) {
throw new org.apache.avro.AvroRuntimeException(e);
}
```
which references AvroMissingFieldException - that only exists in avro 1.9+ - with this:
```java
catch (java.lang.Exception e) {
throw e instanceof org.apache.avro.AvroRuntimeException ? (org.apache.avro.AvroRuntimeException) e : new org.apache.avro.AvroRuntimeException(e);
}
```
> remove references to new avr exception classes from builders for broader compatibility

- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/OldSchemaConstructableUsageDetector.java
> fix NPE in OldSchemaConstructableUsageDetector for methods without a local variable table

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson1Utils.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/AvroCompatibilityHelperAvro17Test.java
- helper/tests/helper-tests-common/src/main/resources/RecordWithRecursiveTypesAndDefaults.avsc
When creating fields with the FieldBuilder and supplying a default
value to the field builder by using the adapter's genericDefaultValue
from an existing field, it will return a `GenericData.EnumSymbol`.
This changeset makes Jackson1Utils `GenericData.EnumSymbol` aware.
> Adding support for defaults from EnumSymbols

- avro-fastserde/build.gradle
- avro-fastserde/regenerate_avro.sh
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/ExceptionUtils.java
- helper/impls/helper-impl-110/build.gradle
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/tests/codegen-110/build.gradle
- helper/tests/helper-tests-110/build.gradle
- helper/tests/helper-tests-allavro/build.gradle
- parser/build.gradle
> preserve root cause of SpecificCompiler instantiation failure, also avro 1.10.2

- helper/tests/helper-tests-110/build.gradle
- helper/tests/helper-tests-110/src/jmh/java/com/linkedin/avroutil1/compatibility/avro110/NewRecord.java
- helper/tests/helper-tests-111/build.gradle
- helper/tests/helper-tests-111/src/jmh/java/com/linkedin/avroutil1/compatibility/avro111/NewRecord.java
- helper/tests/helper-tests-14/build.gradle
- helper/tests/helper-tests-14/src/jmh/java/com/linkedin/avroutil1/compatibility/avro14/NewRecord.java
- helper/tests/helper-tests-15/build.gradle
- helper/tests/helper-tests-15/src/jmh/java/com/linkedin/avroutil1/compatibility/avro15/NewRecord.java
- helper/tests/helper-tests-16/build.gradle
- helper/tests/helper-tests-16/src/jmh/java/com/linkedin/avroutil1/compatibility/avro16/NewRecord.java
- helper/tests/helper-tests-17/build.gradle
- helper/tests/helper-tests-17/src/jmh/java/com/linkedin/avroutil1/compatibility/avro17/NewRecord.java
- helper/tests/helper-tests-18/build.gradle
- helper/tests/helper-tests-18/src/jmh/java/com/linkedin/avroutil1/compatibility/avro18/NewRecord.java
- helper/tests/helper-tests-19/build.gradle
- helper/tests/helper-tests-19/src/jmh/java/com/linkedin/avroutil1/compatibility/avro19/NewRecord.java
- helper/tests/helper-tests-allavro/build.gradle
To run an individual benchmark, for example:
`$ ./gradlew :helper:tests:helper-tests-111:jmh`
To run all the benchmarks:
`$ ./gradlew :helper:tests:helper-tests-allavro:jmh`
NOTE TO REVIEWERS: You only need to review the benchmark code for Avro 1.11. All the others are exact copies of that code, except that methods not supported in those versions have been removed.
Here's example output from running them on my laptop. The units are "operations per millisecond", so larger numbers indicate better performance. The naming convention is `NewRecord.<compat|native><Vanilla|Builder><version>`, where:
* `native` means using the SpecificRecords as generated by raw Avro; `compat` means using the SpecificRecords that were post-processed by the compat helper.
* `Vanilla` means creating the …
> [helper] Add microbenchmarks covering SpecificRecord creation.

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/tests/helper-tests-110/src/jmh/java/com/linkedin/avroutil1/compatibility/avro110/NewRecord.java
- helper/tests/helper-tests-16/src/jmh/java/com/linkedin/avroutil1/compatibility/avro16/NewRecord.java
- helper/tests/helper-tests-17/src/jmh/java/com/linkedin/avroutil1/compatibility/avro17/NewRecord.java
- helper/tests/helper-tests-18/src/jmh/java/com/linkedin/avroutil1/compatibility/avro18/NewRecord.java
- helper/tests/helper-tests-19/src/jmh/java/com/linkedin/avroutil1/compatibility/avro19/NewRecord.java
The introduction of a `private Builder(boolean)` constructor is ugly,
but it's the simplest way I found to deal with this issue. It's private
and not exposed, so the ugliness shouldn't bleed into anything else.
Fixes #220. In addition, since 1.11 codegen can now be processed into
being compatible with older runtimes, add some benchmark methods that
weren't possible before.
Here's the benchmark output from my laptop, only the interesting bits
(the parts that changed):
Before:
```
$ ./gradlew :helper:tests:helper-tests-110:jmh
...
NewRecord.processed110Builder  thrpt   10    1307.549 ±    282.097  ops/ms
NewRecord.processed17Builder   thrpt   10    1070.114 ±    259.597  ops/ms
NewRecord.processed18Builder   thrpt   10    1231.135 ±    204.276  ops/ms
NewRecord.processed19Builder   thrpt …
```
> [helper] Avoid expensive calls in Builder constructors.

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveArrayList.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/PrimitiveArrayListTest.java
This line is the issue:
System.arraycopy(elementsArray, 0, newElements, 0, location - 1);
The fifth input is the length of the elements to copy.
Assuming the size of previous array is 2, like [111, 222]; and we call PrimitiveLongArrayList.add(2, 0L) , position is 2, so we end up running System.arraycopy(elementsArray, 0, newElements, 0, 2 - 1) , only copying the first element from the previous backing array to the new backing array.
In another word, as long as we call PrimitiveLongArrayList.add(PrimitiveLongArrayList.size(), 0) to expand the array list, we will lose the last element from the original list. The correct implementation should be:
System.arraycopy(elementsArray, 0, newElements, 0, location);
> Fix bug in PrimitiveArrayList add method

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/tests/helper-tests-14/src/test/java/com/linkedin/avroutil1/compatibility/avro14/CodeTransformationsAvro14Test.java
Avro 1.4/1.5 generate broken (uncompilable) code when the schema has
escaped chars in strings. We fix such code in the compat helper by:
* First, undoing the damage (unescaping `\"` back to `"`),
* Then, escaping backslashes (escaping `\` to `\\`), and
* Finally, re-escaping the quotes (from `"` to `\"`).
If we are replacing the schema with an "alternative", since the alt
comes directly from JSON, and not from codegen, we escape it using
a standard function (`StringEscapeUtils.escapeJava`), and don't bother
fixing up the original broken code.
If the code was generated by Avro 1.6 or later, it would be correctly
escaped to begin with, so there's nothing more to do.
The test was copied from PR #252, courtesy of @radai-rosenblatt.
Fixes #253.
> [helper] Fix broken escaping in codegen by Avro 1.4/1.5.

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/tests/helper-tests-111/src/test/java/com/linkedin/avroutil1/compatibility/avro111/CodeTransformationsAvro111Test.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/CodeTransformationsAvro19Test.java
- helper/tests/helper-tests-common/src/main/resources/RecordWith144Fields.avsc
- helper/tests/helper-tests-common/src/main/resources/RecordWith432Fields.avsc
also added a TODO for a possible way to keep custom coder methods even under older avro
> allow keeping custom coder methods in generated code targeted at modern avro, strip them out if theyre too big

- avro-codegen/build.gradle
- build.gradle
- helper/tests/codegen-110/build.gradle
- helper/tests/codegen-111/build.gradle
- helper/tests/codegen-14/build.gradle
- helper/tests/codegen-15/build.gradle
- helper/tests/codegen-16/build.gradle
- helper/tests/codegen-17/build.gradle
- helper/tests/codegen-18/build.gradle
- helper/tests/codegen-19/build.gradle
Updating Log4j version to 2.17.0 because of CVE-2021-45105 vulnerability.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105
> Update Log4j to 2.17.0 to address CVE-2021-45105

- avro-codegen/build.gradle
- build.gradle
- helper/tests/codegen-110/build.gradle
- helper/tests/codegen-111/build.gradle
- helper/tests/codegen-14/build.gradle
- helper/tests/codegen-15/build.gradle
- helper/tests/codegen-16/build.gradle
- helper/tests/codegen-17/build.gradle
- helper/tests/codegen-18/build.gradle
- helper/tests/codegen-19/build.gradle
Updating Log4j version to 2.17.1 because of CVE-2021-44832 vulnerability.
https://nvd.nist.gov/vuln/detail/CVE-2021-44832
> Update Log4j to 2.17.1 to address CVE-2021-44832

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/GoodClass.java
This util method is actually checking if a record is a `GenericData.Record` instead of an `org.apache.avro.generic.GenericRecord`. So, update its method name and doc to be more precise.
> Change util method name from isGenericRecord to isGenericDataRecord and update its Javadoc accordingly

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroSchemaUtil.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/FieldBuilder111.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/FieldBuilder19.java
- helper/tests/codegen-14/src/main/compat-avro/under14/RecordWithComplexDefaults.avsc
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java
When transforming a default value that has a map somewhere inside, and
when that map has null values in it, we need to transform those nulls
into actual objects. Otherwise, Avro croaks like so:
```
java.lang.NullPointerException
at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:96)
at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:68)
at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:53)
at org.apache.avro.Schema$Field.<init>(Schema.java:596)
at com.linkedin.avroutil1.compatibility.avro110.FieldBuilder110.build(FieldBuilder110.java:104)
at com.linkedin.avroutil1.compatibility.FieldBuilderTest.setDefaultValues(FieldBuilderTest.java:118)
at com.linkedin.avroutil1.compatibility.FieldBuilderTest.testDefaultValuesInterop(FieldBu …
```
> [helper] Transform null values within default values into null marker objects.

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelperDefaultsTest.java
1. Added getNullableGenericDefaultValue to check if schema field has default value. If so returns the default value otherwise returns null. So, null means that the field does not have default value or field is of type NULL or union field with null and null being the first member.
2. Un deprecated createSchemaField as it is easier to invoke compared to newField if there there are more usage within a file or within a single method. This will help make code more readable and reduce the code size.
3. Added some test for the newly added methods.
> Added getCompatibleDefaultValue method and un-deprecation of createSchemaField

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
Un-deprecate overloaded createSchemaField method. Usage of this method will help reduce consumer code size and make more readable when used multiple times within a class or method.
> Un-deprecate overloaded createSchemaField method.

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson1Utils.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson2Utils.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110AvscWriter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111AvscWriter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14AvscWriter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15AvscWriter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16AvscWriter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17AvscWriter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18AvscWriter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19AvscWriter.java
- helper/tests/helper-tests-allavro/build.gradle
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvscWriterDefaultNumericsTest.java
- settings.gradle
fixes #289
For `int`s and `long`s, integer values that are represented as `float`s/`double`s (i.e. `-1.0`, `0.0`) will be converted to an `int`/`long` (i.e. `-1`, `0`). If the number is a true double (i.e. `3.14159`) we will warn and passthrough.
For `float`s and `double`s, integer values (i.e. `-1`, `0`) are represented with a decimal point and a trailing 0 (i.e. `-1.0`, `0.0`).
> [AvscWriter] enforce uniform numeric defaults on write

- build.gradle
The `parser` package is needed for parsing Avsc Schemas
> adds 'parser' as a publishable artifact

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson1Utils.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson2Utils.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaParseConfiguration.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110SchemaValidator.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/backports/Avro110DefaultValuesCache.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111SchemaValidator.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/backports/Avro111DefaultValuesCache.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14SchemaValidator.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/backports/Avro14DefaultValuesCache.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15SchemaValidator.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/backports/Avro15DefaultValuesCache.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16SchemaValidator.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/backports/Avro16DefaultValuesCache.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17SchemaValidator.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/backports/Avro17DefaultValuesCache.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18SchemaValidator.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/backports/Avro18DefaultValuesCache.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19SchemaValidator.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/backports/Avro19DefaultValuesCache.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelperParsingTest.java
this allows configuring validation of numeric default value types separately from the more "coarse" validation of default values.
this allows accepting 0.0 for integers and 0 for floating points.
note that modern avro (>= 1.10) performs this validation as part of default value validation (if enabled)
> introduce SchemaParseConfiguration.LOOSE_NUMERICS and allow control over validation of numeric default value types

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson1Utils.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson2Utils.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/ConfigurableSchemaComparator.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/SchemaComparisonConfiguration.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Utils.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/ConfigurableSchemaComparatorTest.java
its generally impossible to write "portable" (across avro versions) code that relies on the behavior of Schema.equals(), for the following reasons:
1. avro 1.4 discards non-string properties on types and fields, yet props are part of equals(). this means that schemas that are equals() under 1.4 are not so under more modern avro
2. modern versions of avro do not allow floating point default values for integer fields and vice versa. older avro did not complain about those and it is sometimes required to support "loose" comparison of those for legacy reasons
3. avro Schema.equals() does not take aliases into account yet there are situations where differences in aliases are important
4. similarly to above, we want to be able to compare logical types and java string types
class …
> add ConfigurableSchemaComparator class to allow for nuance when testing for schema equality

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson1Utils.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson2Utils.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaParseConfiguration.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelperParsingTest.java
avro uses a buffered json parser and ignores anything left in the buffer after reading the schema out,
this means that trailing "junk content" after the end of the schema is tolerated.
this PR adds validation to Helper.parse() to look for such junk
> add validation to Helper.parse() for contents after the end of an avsc (see AVRO-3560)

- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
I did not realize that  `com.linkedin.avro.codegen.CodeGenerator` was not using @li-ukumar's Specific Record code generation. I have reverted most of that change and plugged in `SpecificRecordClassGenerator` instead.
> Use SpecificRecordGenerationConfig instead of CodeGenerator

- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/CodeGenOpConfig.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/FileSystemSchemaSetProvider.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/VanillaProcessedCodeGenOp.java
- avro-builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
- avro-builder/src/test/resources/test-projects/test-includes-option/common/ImportableSchema.avsc
- avro-builder/src/test/resources/test-projects/test-includes-option/input/SimpleRecord.avsc
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvroParseContext.java
This PR adds support for the `--include` statement that `VanillaProcessedCodeGenOp` already implements.
One detail of note: if there are no `--include` schemas, all `--input` schemas are allowed to import from each other. Is this the functionality we want?
> adds support for importable source to avro-util's codegen/builder

- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/AvroSchemaUtils.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/BuilderPluginContext.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/Operation.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/OperationContext.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/VanillaProcessedCodeGenOp.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/plugins/BuilderPlugin.java
- avro-builder/src/test/java/com/linkedin/avroutil1/builder/plugins/TestBuilderPlugin.java
* separates operation context from plugin context
* Adds `Set<File> avroFiles` to operation context
* Not sure if we should add `Set<AvroSchema> avroSchemas` since they won't necessarily be generated if we use vanilla codegen
> [builder] separate plugin context from operation context

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
Previously, fast-avro would put all the libs in the same folder of avro jar
in the compilation classpath of generated fast classes, which sometimes
triggers some weird issues since some unnecessary libs might be corrupted,
this code change removes the unnecessary libs by inferring all the compilation
dependencies while generating the fast classes.
> Removed unnecessary libs during fast-class compilation

- avro-builder/tests/codegen-14/src/main/avro/vs14/DollarSignInDoc.avsc
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/DollarSignInAvroTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
- avro-codegen/src/test/resources/schemas/DollarSignInDoc.avsc
JavaPoet treats $ as a string literal. Replacing with $$ to handle it. This will result in a single $ sign after build.
> Handle literal sign in JavaPoet during codegen

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/VanillaProcessedCodeGenOp.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGenerationConfig.java
Enforces using Avro 702 Handling in 2 ways
1. Changes the `--enableAvro702Handling` default value from `false` -> `true`
2. Logs a warning if the user attempts to set the value to `true`
Eventually, we will deprecate this field, but for now we can track who still tries to disable 702 handling.
This PR also adds handling of the `--minAvroVersion` to avro-util's custom codegen.
> Enforces using Avro 702 Handling & adds min avro version config

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/tests/helper-tests-111/src/test/java/com/linkedin/avroutil1/compatibility/avro111/AvroCompatibilityHelperProps111Test.java
- helper/tests/helper-tests-14/src/test/java/com/linkedin/avroutil1/compatibility/avro14/AvroCompatibilityHelperProps14Test.java
- helper/tests/helper-tests-16/src/test/java/com/linkedin/avroutil1/compatibility/avro16/AvroCompatibilityHelperProps16Test.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/AvroCompatibilityHelperProps17Test.java
- helper/tests/helper-tests-18/src/test/java/com/linkedin/avroutil1/compatibility/avro18/AvroCompatibilityHelperProps18Test.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/AvroCompatibilityHelperProps19Test.java
> Add AvroCompatibilityHelper.getAllPropNames() API to return all prop names.

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/tests/codegen-110/build.gradle
- helper/tests/codegen-110/src/main/compat-avro-w-builders-min-avro18/under110wbuildersmin18/NormalRecordWithoutReferences.avsc
- helper/tests/codegen-111/build.gradle
- helper/tests/codegen-111/src/main/compat-avro-w-builders-min-avro18/under111wbuildersmin18/NormalRecordWithoutReferences.avsc
- helper/tests/codegen-18/build.gradle
- helper/tests/codegen-18/src/main/compat-avro-w-builders-min-avro18/under18wbuildersmin18/NormalRecordWithoutReferences.avsc
- helper/tests/codegen-19/build.gradle
- helper/tests/codegen-19/src/main/compat-avro-w-builders-min-avro18/under19wbuildersmin18/NormalRecordWithoutReferences.avsc
- helper/tests/helper-tests-110/src/test/java/com/linkedin/avroutil1/compatibility/avro110/CodeTransformationsAvro110Test.java
- helper/tests/helper-tests-111/src/test/java/com/linkedin/avroutil1/compatibility/avro111/CodeTransformationsAvro111Test.java
- helper/tests/helper-tests-18/src/test/java/com/linkedin/avroutil1/compatibility/avro18/CodeTransformationsAvro18Test.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/CodeTransformationsAvro19Test.java
When performing CodeTransformations, we must ensure that we insert the cached
builder instance _after_ the MODEL$ definition. Fix one case where this wasn't
being done properly, viz., codegen with minAvroVer >= 1.8.
Without this fix, on susceptible cases, calling `new Builder()` is enough to
cause an NPE. Example:
```
java.lang.NullPointerException
at under19wbuildersmin18.NormalRecordWithoutReferences$Builder.<init>(NormalRecordWithoutReferences.java:432)
at under19wbuildersmin18.NormalRecordWithoutReferences$Builder.<init>(NormalRecordWithoutReferences.java:422)
at under19wbuildersmin18.NormalRecordWithoutReferences$Builder.<init>(NormalRecordWithoutReferences.java:401)
at under19wbuildersmin18.NormalRecordWithoutReferences.newBuilder(NormalRecordWithoutReferences.java:368)
at …
```
> Fix cached builder instance generation.

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/ClasspathSchemaSet.java
- avro-builder/builder/src/test/java/build/generated/SimpleRecord.java
- avro-builder/builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
- avro-builder/builder/src/test/java/simpleproject/SimpleRecord.java
- avro-builder/builder/src/test/resources/test-projects/classpath-project/input/SchemaWithClasspathImport.avsc
supports `--includeClasspath` flag. When resolving references, unresolved schemas will be searched for on the classpath. Some changes were needed to codegen setup in order to not generate `.java` specific records for classpath files.
One option, if deemed fit, would be to move the import from classpath functionality into `AvroParseContext`. However, since this functionality is not part of org.apache.avro, it is probably best to keep it separate.
unit tests added as well
> adds import from classpath functionality to AvroUtilCodeGenOp

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_10/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_5/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_6/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_9/UnionOfRecordsWithSameNameEnumField_SpecificDeserializer_5893918162876115133_5893918162876115133.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/backport/ResolvingGrammarGenerator.java
- avro-fastserde/src/test/avro/unionOfRecordsWithSameNameEnumField.avsc
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastSpecificDeserializerGeneratorTest.java
After upgrading our avro version to 1.9 from 1.4, we discovered that FastDeser generation started failing. I was able to recreate this failure with a simple unit test involving a union of two records that have the same field name, but different enum types. The exception we see is:
```
Caused by: java.lang.ClassCastException: class com.linkedin.avro.fastserde.backport.Avro19Resolver$ErrorAction cannot be cast to class com.linkedin.avro.fastserde.backport.Avro19Resolver$EnumAdjust (com.linkedin.avro.fastserde.backport.Avro19Resolver$ErrorAction and com.linkedin.avro.fastserde.backport.Avro19Resolver$EnumAdjust are in unnamed module of loader 'app')
at com.linkedin.avro.fastserde.backport.ResolvingGrammarGenerator.mkEnumAdjustWithDefault(ResolvingGrammarGenerator.java:455)
at …
```
> Fix fast-serdese bug with enums inside of record unions

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
- avro-builder/builder/src/test/resources/test-projects/classpath-dup-project/input/SchemaWithDupImport.avsc
- avro-builder/builder/src/test/resources/test-projects/classpath-dup-project/input/SimpleRecord.avsc
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvroParseContext.java
This PR moves the logic for crawling the classpath for schema imports until after parsing all input files completes. As part of the change, the building of `AvroParseContext`'s indices was moved from `resolveReferences()` (at the very end of parsing) to being updated as each file is `add()`ed to the context. This allows external callers to access these indices instead of needing to reproduce these indices themselves.
> move CP import logic to the end of parsing

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/StringConverterUtil.java
- public Charsequence fields store Utf8s during runtime to support 1.4 functionality.
- type String Accessors 
**Tests:**
- Updated test case to verify getter setter and public field
- tracking build successful with this snapshot
> Store utf8 runtime, String accessors

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_10/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_5/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_6/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_9/RecordWithLargeUnionField_SpecificDeserializer_3405422059761328483_4069749625437031485.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
Bug fix
1. Remove redundant escape chars
2. 65000 limit instad of 65535
> [avro-util] fix large string chunk - remove escape chars

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
- nullable union type ([null, type] or [type/null]) in Builder moved from Object to Type
- DefaultMethodType type for String type in allArg constructor.
> Codegen: Param type update

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/resources/schemas/BuilderTester.avsc
- generate both string and charseq setters (overloaded) for string field types
- and for nullable unions ( null, type OR type,null )
> both string and charseq setters codegen for string field type

- parser/src/main/java/com/linkedin/avroutil1/writer/avsc/AvscSchemaWriter.java
- parser/src/test/java/com/linkedin/avroutil1/writer/avsc/AvscSchemaWriterTest.java
- parser/src/test/resources/schemas/RecordFieldWithProps.avsc
Record field json properties were not being written in AvscSchemaWriter. This PR fixes that bug
> fix record field json properties not being emitted

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
public fields @Deprecated.
Users should prefer using accessors.
> Codegen deprecate public fields

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaComparisonConfiguration.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/ConfigurableSchemaComparator.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Utils.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/ConfigurableSchemaComparatorTest.java
Adds the ability to ignore equality checks on a set of JSON prop names. 
Note that this will only ignore "junk" JSON and not JSON property names that are apart of the Avro spec.
Testing: Unit tests
> Adds ability to ignore json props to ConfigurableSchemaComparator

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/backports/SpecificDatumWriterExt.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/backports/SpecificDatumReaderExt.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/backports/SpecificDatumWriterExt.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/backports/SpecificDatumWriterExt.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/backports/SpecificDatumWriterExt.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/tests/codegen-111/src/main/compat-avro/under111/DeeplyNested.avsc
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/SpecificDataDeadlockTest.java
- helper/tests/helper-tests-allavro/src/test/resources/allavro/serializedOuter.json
so, turns out
```
WRITER$ = new SpecificDatumWriter(SCHEMA$); 
```
creates a deadlock under avro 1.11, since as part of the ctr call it will call SpecificData.getForClass(), which will attempt to re-enter CHM.compute() in SpecificData.classCache.
the solution is to provide the instance of SpecificData to use
```
WRITER$ = new SpecificDatumWriter(SCHEMA$, MODEL$);
```
which is what modern avro does out of the box (supporting logical types in avro is via a per-class instance of SpecificData stored in MODEL$).
since the relevant ctr isnt available before avro ~1.7.4 i added a helper method to access it, making the resulting generated code be
```
WRITER$ = AvroCompatibilityHelper.newSpecificDatumWriter(SCHEMA$, MODEL$)
```
> update generated code post-processing for WRITER$ to avoid deadlock in 1.11

- avro-builder/tests/codegen-110/build.gradle
- avro-builder/tests/codegen-111/build.gradle
- avro-builder/tests/codegen-14/build.gradle
- avro-builder/tests/codegen-15/build.gradle
- avro-builder/tests/codegen-16/build.gradle
- avro-builder/tests/codegen-17/build.gradle
- avro-builder/tests/codegen-18/build.gradle
- avro-builder/tests/codegen-19/build.gradle
- avro-builder/tests/codegen-charseq-method/build.gradle
- avro-builder/tests/codegen-no-utf8-in-putbyindex/build.gradle
- helper/tests/codegen-110/build.gradle
- helper/tests/codegen-111/build.gradle
- helper/tests/codegen-14/build.gradle
- helper/tests/codegen-15/build.gradle
- helper/tests/codegen-16/build.gradle
- helper/tests/codegen-17/build.gradle
- helper/tests/codegen-18/build.gradle
- helper/tests/codegen-19/build.gradle
this drops the 2nd+ run time for ./gradlew :helper:tests:helper-tests-allavro:test down from ~50 seconds to ~8 seconds on my machine
> make testing code-gen tasks declare inputs and outputs for incremental build support

- avro-fastserde/build.gradle
in response to this build failure
>The jmhCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the jmhImplementation configuration instead. Consult the upgrading guide for further information: 
>https://docs.gradle.org/6.5.1/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
> [fastserde] switch jmhCompile to jmhImplementation

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/FileSystemSchemaSetProvider.java
- avro-builder/builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
- avro-builder/builder/src/test/resources/test-projects/simple-project/input/NestedRecord.avsc
- avro-builder/builder/src/test/resources/test-projects/simple-project/input/SimpleRecord.avsc
In https://github.com/linkedin/avro-util/pull/370's `FileSystemSchemaSetProvider.java`, we switched from `catch`ing `JsonProcessingException` to catching all `Exception`s. This meant that `SchemaParseException`s up above were getting thrown on instead of retried. This change fixes that bug.
> [builder] fix exception handling

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/FileSystemSchemaSetProvider.java
- avro-builder/builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
This is a follow up to https://github.com/linkedin/avro-util/pull/442. Non-`JsonProcessingException`s should still be thrown
> [builder] continue throwing non-JsonProcessingExceptions

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroRecordUtil.java
- AvroRecordUtil deepcopy handles Union and Charseq type
- newBuilder expected string type is same as field type used in builder.
> Updated codegen builder initializer and Avrorecord deepcopy

- avro-builder/builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
- avro-builder/builder/src/test/resources/test-projects/test-underscores/input/RecordWithUnderscores.avsc
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
A record with a field name that includes underscores (i.e. `field_with_underscores_`) has a getter `getFieldWithUnderscores()` in vanilla avro. However, in our custom avro codegen, it was getting generated as `getField_with_underscores_()`. This PR aligns our custom codegen with vanilla avro codegen.
As a note, this is the only non-alphanumeric symbol allowed in Avro field names. The regex for avro field names, according to [the docs](https://avro.apache.org/docs/1.10.2/spec.html), is as follows: `[A-Za-z_][A-Za-z0-9_]*`
> [avro-codegen] Fix underscore issue in getter/setter names

- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/resources/schemas/TestProblematicRecord.avsc
In the generated `get(int field)` method, if the field name was `field`, the local method argument was referenced, not the class field. Prefixing thos lookups with `this.` fixes this issue.
Alternatively, we could consider postfixing all method arguments with `$` or in some way that there would never be a conflict (I imagine this is why `SCHEMA$` is used).
Before
After
> [codegen] reference class fields using 'this.'

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AbstractSchemaBuilder.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/SchemaBuilderTest.java
- helper/tests/helper-tests-allavro/src/test/resources/allavro/RecordWithEmptyFieldList.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/RecordWithEmptyFieldListInNestedField.avsc
Fix schema parsing when record has empty field list.
AvroCompatibilityHelper.newSchema(schemaA) API ignores empty field list. For example:
when the schema has empty field like
SchemaA:
{"type":"record","name":"StatsTransaction","fields":[],"schemaType":"DocumentSchema","version":1}
Then call the AvroCompatibilityHelper.newSchema(SchemaA).setType(Type.RECORD).build();
will return:
{"type":"record","name":"StatsTransaction","schemaType":"DocumentSchema","version":1}
This also ignore field for empty nexted subrecords field.
This PR is to fix this issue by allowing empty field list in record
> Fix schema creation when original schema's record has empty field list

- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordInherit.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordInnerNamespaceInherit.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordInnerNamespaceNoInherit.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordNoInherit.avsc
commit #446 added support for canonical form of avro files, which updated AvscWriter to follow a defined order of keys while writing avsc, where 'type' is after 'name' and 'namespace'
Updating Unit tests to expect the same
> Updating Unit tests to expect correct order of avsc writer

- fastserde/avro-fastserde/build.gradle
- FastSerde module is Avro version independent, but still require Avro library to compile
- Default version is 1.10 and due to build changes this version leaked to POM file causing dependency issues
- This change removes explicit dependency on Avro from POM file
> Updated build to exclude explicit dependency on Avro from FastSerde build

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastNestedArrayTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorBase.java
The test for nested arrays was incorrect.  Update the tests in `FastNestedArrayTest.java` to correctly validate the test.
Fix bug processing nested array discovered by updating test.
> Fix test case and code for nested arrays

- parser/src/main/java/com/linkedin/avroutil1/model/AvroSchemaDifference.java
- parser/src/main/java/com/linkedin/avroutil1/util/ConfigurableAvroSchemaComparator.java
- parser/src/test/java/com/linkedin/avroutil1/util/ConfigurableAvroSchemaComparatorTest.java
- parser/src/test/resources/schemas/TestJsonPropsInFields1.avsc
- parser/src/test/resources/schemas/TestJsonPropsInFields2.avsc
This check has already been added to `ConfigurableSchemaComparator` in #433. This PR adds the same functionality to `ConfigurableAvroSchemaComparator`.
> Add json prop check to ConfigurableAvroSchemaComparator

- avro-codegen/build.gradle
- parser/src/main/java/com/linkedin/avroutil1/util/ConfigurableAvroSchemaComparator.java
- parser/src/test/java/com/linkedin/avroutil1/util/ConfigurableAvroSchemaComparatorTest.java
This feature was added to `ConfigurableSchemaComparator` but is missing from `ConfigurableAvroSchemaComparator`.
> add missing jsonPropNameIgnore feature to AvroSchemaComparator

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvscGenerationConfig.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvscWriter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110AvscWriter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111AvscWriter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14AvscWriter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15AvscWriter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16AvscWriter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17AvscWriter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18AvscWriter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19AvscWriter.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/AvroUtilSchemaNormalizationTest17.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/AvroUtilSchemaNormalizationTest19.java
- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordInherit.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordInnerNamespaceInherit.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordInnerNamespaceNoInherit.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/ComplexRecordNoInherit.avsc
Adding a legacy option in Avsc writer to generate Avsc before normalization was introduced.
Only canonicalization configs to use non-legacy option.
Some use cases Hash the serialized schemas and are now incompatible with the normalized changes. While the long-term viability of some of these usecases are questionable, in short term it means normalization will break their systems.
Updated Unit tests
snapshot on
- `fdp-utils` : https://lva1-app63607.corp.linkedin.com/s/rnisgewbdaj4e
- `avro-schemas` : https://lva1-app63607.corp.linkedin.com/s/ooz7ieoavr3gc
> Legacy schema writer option

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvscWriter.java
- helper/helper/src/main/java/com/linkedin/avroutil1/normalization/AvroUtilSchemaNormalization.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110AvscWriter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111AvscWriter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14AvscWriter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15AvscWriter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16AvscWriter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17AvscWriter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18AvscWriter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19AvscWriter.java
- helper/tests/helper-tests-110/src/test/java/com/linkedin/avroutil1/compatibility/avro110/Avro110AvscWriterTest.java
- helper/tests/helper-tests-111/src/test/java/com/linkedin/avroutil1/compatibility/avro111/Avro111AvscWriterTest.java
- helper/tests/helper-tests-14/src/test/java/com/linkedin/avroutil1/compatibility/avro14/Avro14AvscWriterTest.java
- helper/tests/helper-tests-15/src/test/java/com/linkedin/avroutil1/compatibility/avro15/Avro15AvscWriterTest.java
- helper/tests/helper-tests-16/src/test/java/com/linkedin/avroutil1/compatibility/avro16/Avro16AvscWriterTest.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/Avro17AvscWriterTest.java
- helper/tests/helper-tests-18/src/test/java/com/linkedin/avroutil1/compatibility/avro18/Avro18AvscWriterTest.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/Avro19AvscWriterTest.java
legacy writer support was added in 0.3.3.
Adding plugin support for special handling of json props for legacy use cases as well.
build, 
Unit tests
avro-schemas scan : https://lva1-app63607.corp.linkedin.com/s/eteghjt2aq5s6
> AvscWriter plugin support in legacy writer

- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
BUG=FI-13182
Closes #302
Optimize enum field deserialization #499
> Optimized fastserde enum field deserialization

- avro-builder/tests/codegen-14/src/main/avro/vs14/ThousandField.avsc
- avro-builder/tests/codegen-19/src/main/avro/vs19/ThousandField.avsc
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
This change will break up generated customDecode method into small subMethods while keeping the functionality consistent.
Since generated customDecode method can be large for larger schemas, it could exceed size limit 64k. Splitting method into smaller subMethods avoids it.
Issue: https://github.com/linkedin/avro-util/issues/257
Added UT with a 1000 field record round trip ser/deserialization.
`Errors out on current master`
> Codegen : Custom decode method broken into subMethods

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastStringableTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorBase.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/Utils.java
It used to leverage the Avro fingerprinting, which is based on the "parsing canonical form" of the schema, but this ignores properties such as which class to use for String deserialization. This is a problem in cases where we wish to deserialize the same schema both with and without Java Strings, since the cache will return the same deserializer for both, ultimately leading to class cast issues.
The new approach is to simply take the hash code of the full string of the schema.
> Tweaked the fast-avro schema fingerprinting logic

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastGenericSerializerGeneratorTest.java
- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastSpecificSerializerGeneratorTest.java
- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastStringableTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
In the past, we updated fast deserializer to support large method splitting, and this code change is leveraging the similar logic to split large method in fast serializer.
> [fast-avro] Added logic to split large method for fast serializer

- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeBase.java
In one of our use-cases, we noticed this compilation failure:
```
FastSerdeBase [INFO] Starting compilation for the generated source file: <redacted>/MultiGetResponseRecordV1_GenericDeserializer_1339531883776153861_1339531883776153861.java 
warning: Supported source version 'RELEASE_6' from annotation processor 'org.antlr.v4.runtime.misc.NullUsageProcessor' less than -source '1.8'
error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider lombok.launch.AnnotationProcessorHider$AnnotationProcessor not found
...
Caused by: com.linkedin.venice.exceptions.VeniceException: Failed to generate fast generic de-serializer for Avro schema: {"type":"record","name":"MultiGetResponseRecordV1","namespace":"com.linkedin. …
```
> Disable annotation processing in the runtime compiler

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/build.gradle
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
- avro-codegen/src/test/resources/schemas/TwoThousandField.avsc
Split generated Builder constructors and build() in avro java bindings into chunks (size 25 fields each) if a schema is large (>50 fields)
Java has a method size limit which can theoritically be breached if schema is too large.
this change will split Builder constructors into multiple "chunks" of size 25 fields each if total number of fields is >50.
build and UT which generates and compiles a schema with 2k fields
> Avro codegen : Split builder constructor and build() if #fields > 50

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson1Utils.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/Jackson2Utils.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110AvscWriter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111AvscWriter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17AvscWriter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18AvscWriter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19AvscWriter.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/AvroUtilSchemaNormalizationTest17.java
- helper/tests/helper-tests-17/src/test/resources/PropRecord1.avsc
- helper/tests/helper-tests-17/src/test/resources/PropRecord2.avsc
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/AvroUtilSchemaNormalizationTest19.java
- helper/tests/helper-tests-19/src/test/resources/PropRecord1.avsc
- helper/tests/helper-tests-19/src/test/resources/PropRecord2.avsc
Make json property values deterministic if they are object type in Avro schema canonical form.
The current version of avro schema canonical form can be non-deterministic if a json property is of object type and its internal keys may change order. 
Fixing that by recursively sorting json properties alphabetically (by key name) if they are of object type.
Added unit tests
> Canonicalization : sorting json property values by key if they are object type

- avro-builder/builder-spi/src/main/java/com/linkedin/avroutil1/builder/operations/OperationContext.java
- avro-builder/builder-spi/src/main/java/com/linkedin/avroutil1/builder/operations/SchemaSet.java
- avro-builder/builder-spi/src/main/java/com/linkedin/avroutil1/builder/plugins/BuilderPluginContext.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/OperationContextBuilder.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenPlugin.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilOperationContextBuilder.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/ClasspathSchemaSet.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/FileSystemSchemaSetProvider.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/ResolverPathSchemaSet.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/SchemaSetProvider.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/SimpleSchemaSet.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/vanilla/VanillaProcessedCodeGenOp.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
Decouple schema parsing (fast) from code generation (slow) to be able to run avro codegen and plugins in parallel.
Remove dead code in SpecificRecordGenerator by following IDE warnings.
> Decouple schema parsing from code generation

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenPlugin.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
Avoid generating batches and use parallel stream
> Improve performance of avro codegen

- avro-builder/builder-spi/src/main/java/com/linkedin/avroutil1/builder/plugins/BuilderPluginContext.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- parser/src/main/java/com/linkedin/avroutil1/writer/avsc/AvscSchemaWriter.java
AvscSchemaWriter currently creates a DOM object and then serializes it into a string. This wastes both CPU and memory. Instead use the Jackson streaming API to directly serialize to string. There are APIs available to get a DOM object from a JsonGenerator if needed for debugging purposes.
Add more logging and fix parallelism inside SchemaBuilder.
> Improve performance of AvscSchemaWriter

- avro-builder/builder-spi/src/main/java/com/linkedin/avroutil1/builder/util/StreamUtil.java
This prevents processes from staying alive for a minute just waiting for idle timeout to expire on threads after actual work finishes.
> Reduce keep alive time of thread pool to 100ms

- avro-builder/builder/src/test/resources/test-projects/classpath-project/input/SchemaWithClasspathImport.avsc
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
Before, we would incorrectly generate referenced schemas from classpath/resolver path if they were referenced from an array/map. This change fixes that by checking `getRef() == null` first before generating nested schemas (referenced in a map/array)
> [schema builder] don't generate ref'ed arrays and maps

- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java
- parser/src/test/java/com/linkedin/avroutil1/parser/avsc/AvscParserTest.java
- parser/src/test/resources/schemas/RecordWithMapOfUnion.avsc
Adding `case UNION` in avsc parser handling of default values
Maps/Lists can have their item/value types as unions. Handling such schemas with default values.
Added unit tests
Build
> Added handling of union type in AvscParser 

- avro-builder/builder-spi/src/main/java/com/linkedin/avroutil1/builder/util/StreamUtil.java
methods like **filter** and **map** on stream are lazy. They just create a new stream. Traversal of the pipeline source does not begin until the terminal operation of the pipeline is executed.
The **StreamUtil** wants the **map** method executed for each batch in the thread pool Asynchronously, so we should make the stream pipeline executed in the thread-pool for the reason mentioned above.
Here the collect is the terminal operation that triggers the stream execution.
> fix StreamUtil to execute the map function for each batch in the thread pool

- fastserde/avro-fastserde-tests-common/src/test/avro/primitiveArrays.avsc
- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/primitives/FastSerdePrimitivesArrayTest.java
- fastserde/avro-fastserde-tests110/build.gradle
- fastserde/avro-fastserde-tests111/build.gradle
- fastserde/avro-fastserde-tests14/build.gradle
- fastserde/avro-fastserde-tests15/build.gradle
- fastserde/avro-fastserde-tests16/build.gradle
- fastserde/avro-fastserde-tests17/build.gradle
- fastserde/avro-fastserde-tests18/build.gradle
- fastserde/avro-fastserde-tests19/build.gradle
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/coldstart/ColdPrimitiveBooleanList.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/coldstart/ColdPrimitiveDoubleList.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/coldstart/ColdPrimitiveIntList.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/coldstart/ColdPrimitiveLongList.java
Just a minor fix.
The main change is in 4 classes:
- `ColdPrimitiveBooleanList`
- `ColdPrimitiveDoubleList`
- `ColdPrimitiveIntList`
- `ColdPrimitiveLongList`
> ColdPrimitive*List classes use correct schema.

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/CharSequenceListView.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/StringListView.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/Utf8ListView.java
Overriding clear method in List views to run clear methods of provided list rather than defaulting on AbstractList implementation.
Generic Array implementation in avro has custom implementation of clear, which is lost if AbstractList's method is used.
build
> Override clear method in custom list views

- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java
FileReader was not being closed during `AvscParser#parse()`. This was causing `Too many open files` in some repositories.
> ensure FileReader `close()`es during avro parse

- fastserde/avro-fastserde-tests-common/src/test/avro/recordWith2Fields.avsc
- fastserde/avro-fastserde-tests-common/src/test/avro/recordWith2FieldsAndDeeplyNestedRecord.avsc
- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastSpecificDeserializerGeneratorTest.java
- fastserde/avro-fastserde-tests111/build/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/FastGenericDeserializerGeneratorTest_shouldSkipRemovedNestedRecord_GenericDeserializer_1090641932_438987109.java
- fastserde/avro-fastserde-tests111/build/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/FastGenericDeserializerGeneratorTest_shouldSkipRemovedRecord_GenericDeserializer_1932590611_1452595291.java
- fastserde/avro-fastserde-tests111/build/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/RecordWithOneNullableText_SpecificDeserializer_1753906665_1009500237.java
- fastserde/avro-fastserde-tests111/build/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/RecordWithOneNullableText_SpecificDeserializer_2111230429_1009500237.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
Populate methods now always have 'customization' argument because deserialize-method(s) of nested records may generate another populate methods that require 'customization' (at least for compilation purposes).
This may happen when record is deserialized with schema having less fields (usually: older schema) AND `populate_...()` helper method is generated on a field for which `recordAction.getShouldRead() == false`, so a bit of bad-luck is also needed.
In the added unit-test, without fix the methods chain is:
```
deserialize(RecordWithOneNullableText reuse, Decoder decoder, DatumReaderCustomization customization)
--> deserializeRecordWithOneNullableText0((reuse), (decoder), (customization))
--> populate_RecordWithOneNullableTextAndDeeplyNestedRecord0((RecordWithOneNullableTextAndDeeplyNeste …
```
> [fast-avro][deserializer] Populate methods always with 'customization' argument

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/StringListView.java
Adding handling for Utf8 type in StringListView.addAll method.
Even if `addAll` method metions `<? extends String>`, this should still catch a collection of Utf8 elements as the compiled code does not have the generic information.
Hence we can type cast the object in the implementation.
> Utf8 and String types supported in StringList√iew.addAll

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/StringListView.java
Making StringListView serializable
- build
- added unit test
> Serializable StringListView

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
When reader and writer schemas are different for fields of type `Fixed`, the deserialized objects are created with `null` schema. This commit fixes that handling and adds a test case for it
Without the fix, the generated class has this:
```
topLevelRecord.put(0, new org.apache.avro.generic.GenericData.Fixed(null, fixedType0));
```
With the fix, the generated class has this:
```
topLevelRecord.put(0, new org.apache.avro.generic.GenericData.Fixed(fixedField0, fixedType0));
```
> Use valid schema for Fixed field when deserializing data

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/UtilsTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumReader.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/Utils.java
Limit the max log size for schema in warning.
More background: Some users transit the warning log via network. When the schema is large, it adds a lot of burden to network.
> Limit the max log size for schema in warning.

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
Fix incorrect check for enableUtf8encoding flag. The incorrect check was preventing from setting/overriding enableUtf8EncodingPutbyIndex flag correctly.
> Fix incorrect check for enableUtf8encoding flag

- .github/workflows/pr.yaml
- .github/workflows/push.yaml
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaComparisonConfiguration.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/ConfigurableSchemaComparator.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/ConfigurableSchemaComparatorTest.java
- parser/src/test/java/com/linkedin/avroutil1/util/ConfigurableAvroSchemaComparatorTest.java
The current comparator doesn't return false when comparing 2 avro schemas that differ just by doc field. This causes compatibility issues when evolving espresso schemas (adding comment in proto updates avro doc field in the current .avsc version instead of generating a new .avsc)
This PR adds support to compare 2 avro schemas and return false if they differ by doc field
Added unit tests `testCompareSchemaDoc` and `testCompareSchemaFieldDoc` in `ConfigurableSchemaComparatorTest`
> Add support for comparing doc field in avro schemas

- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
This fixes #564 by adding classes to the classpath for logical types even when `SchemaAssistant.classFromSchema` is passed `allowLogicalTypes=false`.
This change doesn't come with an accompanying test because the only way to write a failing test would be to build a separate subproject jar for a custom type and another subproject jar for a custom `Conversion` class for each Avro version. It could be done but would complicate the existing test infrastructure.
> Support custom logical types derived from fixed types

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorBase.java
The root cause of the issue here is that when passing the actions to a record, we are not passing in the relevant actions. Rather, the processRecord has been written to take in symbols from arbitrary levels preceding the record symbol and then seek to the correct action inside that. This diff tries to ameliorate this problem slightly by making the logic for maps and arrays consistent. 
The comment in processMap covers the idea of how we now pass the symbols to the the elements and value types for arrays and maps respectively. 
The proper fix for this would be to do this to change the traversal of the symbol tree and visit each symbol just once as well as assert the invariant that we visit all of them. 
Fixes #506 as well as the related problem for nested arrays not mentioned in the …
> Fix nested map and array problems

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
Nullable Enum on the reader side is not handled correctly currently. This change fixes it by following the same behavior that is followed for arrays and maps to account for UnionAdjustAction.
Fixes Issue #180
> Handle Nullable Unions Of Enums Correctly

- fastserde/avro-fastserde-tests-common/src/test/avro/defaultsTest.avsc
- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastDeserializerDefaultsTest.java
- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastStringableTest.java
This is a follow-up PR for https://github.com/linkedin/avro-util/pull/584/  to replace remaining occurrences of example.com URL (see the [search query](https://github.com/search?q=repo%3Alinkedin%2Favro-util+%22http%3A%2F%2Fwww.example%22&type=code)). We want to use un-resolvable URLs in tests to avoid intermittent test failures due to URLs resolving to different IPs.
> Replace remaining occurrences of example.com URL

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
- fastserde/avro-fastserde-tests111/build/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/OuterRecord_GenericDeserializer_998347834_1261326440.java
- fastserde/avro-fastserde-tests111/build/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/Wrapper_GenericDeserializer_1221519218_203960580.java
- fastserde/avro-fastserde-tests111/build/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_11/Wrapper_GenericDeserializer_977858399_369594598.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/Utils.java
The avro 1.8 and before spec says that two records match if their names are the same. However, more recent versions like 1.11 clarify that this matching should be done based on the unqualified name. The unit test added here and our experience with 1.8 at Uber suggest that all Avro versions except 1.5-1.7 use the unqualified name for the actual resolution. Thus, the behavior of the current compatible schema in union finder deviates from the standard avro impl and this change brings the two back in sync.
> Compatible Record In Union Lookup Should Use Unqualified Name

- avro-builder/tests/codegen-110/src/main/avro/vs110/IntsAndLongs.avsc
- avro-builder/tests/codegen-111/src/main/avro/vs111/IntsAndLongs.avsc
- avro-builder/tests/codegen-14/src/main/avro/vs14/IntsAndLongs.avsc
- avro-builder/tests/codegen-15/src/main/avro/vs15/IntsAndLongs.avsc
- avro-builder/tests/codegen-16/src/main/avro/vs16/IntsAndLongs.avsc
- avro-builder/tests/codegen-17/src/main/avro/vs17/IntsAndLongs.avsc
- avro-builder/tests/codegen-18/src/main/avro/vs18/IntsAndLongs.avsc
- avro-builder/tests/codegen-19/src/main/avro/vs19/IntsAndLongs.avsc
- avro-builder/tests/codegen-no-utf8-encoding/src/main/avro/noUtf8Encoding/TestCollections.avsc
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
- avro-codegen/src/test/resources/schemas/IntLongString.avsc
Fixed various issues in SpecificRecordClassGenerator methods overloaded for int/long in https://github.com/linkedin/avro-util/pull/581:
1. Fixed constructor to handle CharSequence transformations. This fixes the compilation error:
A bug in the constructor between version 0.4.30 (before int/long changes) and master branch:
Constructor with the fix:
- Added `IntLongString.avsc` record schema and a test case to `SpecificRecordClassGeneratorTest.testSchema` to verify that the generated java file can be compiled.
- Added an `intField` to `TestCollections.avsc` which is used in [SpecificRecordTest.testNoUtf8Encoding](https://github.com/linkedin/avro-util/blob/5a2c36b47977859c38223b8bc44545d8470fa727/avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest. …
> Fixed various issues in SpecificRecordClassGenerator methods overloaded for int/long
