linkedin/avro-util

- avro-migration-helper/src/main/java/com/linkedin/avro/compatibility/AvroCompatibilityHelper.java
- avro-migration-helper/src/main/java/com/linkedin/avro/compatibility/AvroVersion.java
Signed-off-by: radai-rosenblatt <radai.rosenblatt@gmail.com>
> better detection of runtime avro version

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
Generated deserializer examples:
Generic record:
https://gist.github.com/gaojieliu/7fd3868fcfbe42a2ef5931dbce199091
Specific record:
https://gist.github.com/gaojieliu/dab9819a3ffd571ce973c6fb69158bdb
> Added array reuse support for fast deserializer

- avro-fastserde/regenerate_avro.sh
> Use curl instead of wget for better portability

- avro-codegen/build.gradle
Signed-off-by: radai-rosenblatt <radai.rosenblatt@gmail.com>
> remove unused dependency on ant

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumReader.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumWriter.java
Check isDebugEnabled in FastGenericDatumReader/Writer for better performance.
@radai-rosenblatt @gaojieliu @FelixGV
> Check isDebugEnabled for better performance

- .travis.yml
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastAvroConcurrentHashMap.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeBase.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveBooleanArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveDoubleArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveFloatArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveIntArrayList.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/primitive/PrimitiveLongArrayList.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaValidator.java
Also added the javadoc gradle task to the Travis CI for every commit.
> Addressed JavaDoc build failures

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/StringableRecord_SpecificDeserializer_1822942669987229249_1822942669987229249.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/StringableRecord_SpecificDeserializer_1822942669987229249_1822942669987229249.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/StringableRecord_SpecificDeserializer_1822942669987229249_1822942669987229249.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/StringableRecord_SpecificSerializer_1822942669987229249.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_7/StringableRecord_SpecificSerializer_1822942669987229249.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_8/StringableRecord_SpecificSerializer_1822942669987229249.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastStringableTest.java
> Code gen for FastStringableTest

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeBase.java
The SharedNameTable was introduced to speed up Java complication by using soft references to avoid reallocations. However we have observed severe Memory and GC issue brought by it in fast-avro runtime complication.
The GC issue and heavy memory usage happened when fast-avro needed to process a large number of different schemas. The heap dump of the performance test with 10000 schemas show SharedNameTable consumes ~4GBs memory and it can not be freed from the heap thus causes severe GC issues. Dived into the heap dump further, the SharedNameTable has a static reference to a com.sun.tools.javac.util.List which soft references every single SharedNameTable$NameImpl ever created (so one for each fast serializer that fast-avro has generated and compiled during runtime).
SharedNameTable should …
> Disable sharedNameTable for runtime complication

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/FastStringableTest_javaStringPropertyTest_GenericDeserializer_9185875457190242821_9185875457190242821.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/FastStringableTest_javaStringPropertyTest_GenericDeserializer_713665344968052004_713665344968052004.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/StringableRecord_SpecificDeserializer_1822942669987229249_1822942669987229249.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/FastStringableTest_javaStringPropertyTest_GenericDeserializer_713665344968052004_713665344968052004.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/StringableRecord_SpecificDeserializer_1822942669987229249_1822942669987229249.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastStringableTest_javaStringPropertyTest_GenericSerializer_9185875457190242821.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_7/FastStringableTest_javaStringPropertyTest_GenericSerializer_713665344968052004.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_8/FastStringableTest_javaStringPropertyTest_GenericSerializer_713665344968052004.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastStringableTest.java
@radai-rosenblatt @FelixGV @volauvent
> 'avro.java.string' support in  fast-avro

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/FastStringableTest_javaStringPropertyInsideUnionTest_GenericDeserializer_6238557830396401576_6238557830396401576.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/FastStringableTest_javaStringPropertyInsideUnionTest_GenericDeserializer_4476580127917956418_4476580127917956418.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/FastStringableTest_javaStringPropertyInsideUnionTest_GenericDeserializer_4476580127917956418_4476580127917956418.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_4/FastStringableTest_javaStringPropertyInsideUnionTest_GenericSerializer_6238557830396401576.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_7/FastStringableTest_javaStringPropertyInsideUnionTest_GenericSerializer_4476580127917956418.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/serialization/AVRO_1_8/FastStringableTest_javaStringPropertyInsideUnionTest_GenericSerializer_4476580127917956418.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGeneratorBase.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeBase.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerializerGenerator.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/SchemaAssistant.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastStringableTest.java
@FelixGV @volauvent @radai-rosenblatt
> "avro.java.string" support in union type for fast serializer

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/codec/CachedResolvingDecoder.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/codec/ResolvingDecoder.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/codec/ValidatingDecoder.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/parsing/CachedResolvingGrammarGenerator.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/parsing/CachedSymbol.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/parsing/ResolvingGrammarGenerator.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
Added classes from avro lib: 
1. ResolvingDecoder from avro lib
2. ValidatingDecoder from avro lib
Added new Classes:
1. CachedResolvingDecoder 
2. CachedResolvingGrammarGenerator
3. CachedSymbol
Modified classes: 
1. AvroAdapter
2. Avro14Adapter - Avro110Adapter
3. AvroCompatibilityHelper
> Add CachedResolvingDecoder and related classes. 

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_10/FastGenericDeserializerGeneratorTest_shouldReadFixed_GenericDeserializer_3518023893123209014_3518023893123209014.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/FastGenericDeserializerGeneratorTest_shouldReadFixed_GenericDeserializer_8811953951139265292_8811953951139265292.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_5/FastGenericDeserializerGeneratorTest_shouldReadFixed_GenericDeserializer_8811953951139265292_8811953951139265292.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_6/FastGenericDeserializerGeneratorTest_shouldReadFixed_GenericDeserializer_8811953951139265292_8811953951139265292.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/FastGenericDeserializerGeneratorTest_shouldReadFixed_GenericDeserializer_3518023893123209014_3518023893123209014.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/FastGenericDeserializerGeneratorTest_shouldReadFixed_GenericDeserializer_3518023893123209014_3518023893123209014.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_9/FastGenericDeserializerGeneratorTest_shouldReadFixed_GenericDeserializer_3518023893123209014_3518023893123209014.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
cc @FelixGV @volauvent @radai-rosenblatt
> Fixed a fast-avro bug to return the right schema for de-serialized Fixed type

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/FieldBuilder.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/FieldBuilder14.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/FieldBuilder15.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/FieldBuilder16.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/FieldBuilder17.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/FieldBuilder18.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/FieldBuilder19.java
1. Add FieldBuilder interface and related implementations in impls 1,4 - 1.9.
2. Add FIELD_BUILDER instance and  one method in AvroCompatibilityHelper to create a Schema.Field by cloning from existing Field.
> Add FieldBuilder interface and related implementations 

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
> Changed the fast-avro compile dependency logging level to debug

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeBase.java
@majisourav99 @radai-rosenblatt 
Please take a look at this small fix.
> Changed another fast-avro compile dependency logging level to debug

- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_10/RemovedTypesTestRecord_SpecificDeserializer_4294788212396119963_8592038788392504303.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_4/RemovedTypesTestRecord_SpecificDeserializer_4294788212396119963_8592038788392504303.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_5/RemovedTypesTestRecord_SpecificDeserializer_4294788212396119963_8592038788392504303.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_6/RemovedTypesTestRecord_SpecificDeserializer_4294788212396119963_8592038788392504303.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_7/RemovedTypesTestRecord_SpecificDeserializer_4294788212396119963_8592038788392504303.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_8/RemovedTypesTestRecord_SpecificDeserializer_4294788212396119963_8592038788392504303.java
- avro-fastserde/src/codegen/java/com/linkedin/avro/fastserde/generated/deserialization/AVRO_1_9/RemovedTypesTestRecord_SpecificDeserializer_4294788212396119963_8592038788392504303.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastSpecificDeserializerGeneratorTest.java
- avro-fastserde/src/test/resources/schema/removedTypesTestWithADifferentNamespace.avsc
@FelixGV @radai-rosenblatt 
Please take a look when you have time.
> @gaojieliu Fixed an fast specfic deserializer generation issue when namespace mismatches

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
add new API for boundedMemoryDecoder
> add new API for boundedMemoryDecoder

- avro-codegen/build.gradle
- avro-fastserde/build.gradle
- build.gradle
- helper/helper/build.gradle
> fix published dependencies for codegen, publish spotbugs, kill bintray bits

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroAdapter.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/FieldBuilder.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/FieldBuilder14.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/FieldBuilder15.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/FieldBuilder16.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Utils.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/FieldBuilder17.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/FieldBuilder18.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/FieldBuilder19.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java
- helper/tests/helper-tests-common/src/main/resources/RecordWithFieldProps.avsc
> initial support for field properties in FieldBuilder

- parser/build.gradle
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/BuilderWithLocations.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonArrayExt.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonArrayExtBuilder.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonArrayExtImpl.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonFalseExtImpl.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonNullExtImpl.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonNumberExt.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonNumberExtImpl.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonObjectExt.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonObjectExtBuilder.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonObjectExtImpl.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonReaderExt.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonReaderWithLocations.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonStringExt.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonStringExtImpl.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonStructureExt.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonTrueExtImpl.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonValueExt.java
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonValueExtImpl.java
- parser/src/test/java/com/linkedin/avroutil1/parser/TestJsonParsing.java
- parser/src/test/resources/schemas/TestRecord.avsc
- settings.gradle
would later be used to create a parser for avsc schemas
> initial implementation of a json parser preserving source location of elements

- spotbugs-plugin/README.md
- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/GenericRecordBuilderUsageDetector.java
- spotbugs-plugin/src/main/resources/findbugs.xml
- spotbugs-plugin/src/main/resources/messages.xml
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/BadClass.java
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/GenericRecordBuilderUsageDetectorTest.java
> implement spotbugs detector for usage of GenericRecordBuilder

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelperParsingTest.java
addresses #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/linkedin/avro-util/187)
> add Helper.parse(InputStream)

- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Utils.java
> fix detection of exact avro 1.7 version under classpaths with multiple avro jars

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaParseConfiguration.java
> Make SchemaParseConfiguration.LOOSE validate neither names nor values

- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/AbstractUsageDetector.java
- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/BinaryMessageDecoderUsageDetector.java
- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/BinaryMessageEncoderUsageDetector.java
- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/GenericRecordBuilderUsageDetector.java
- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/SingleSchemaDeserializationDetector.java
- spotbugs-plugin/src/main/resources/findbugs.xml
- spotbugs-plugin/src/main/resources/messages.xml
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/BadClass.java
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/BinaryMessageDecoderUsageDetectorTest.java
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/BinaryMessageEncoderUsageDetectorTest.java
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/GoodClass.java
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/SingleSchemaDeserializationDetectorTest.java
> spotbugs detectors for BinaryMessage codecs and 1-arg deserialization

- parser/src/main/java/com/linkedin/avroutil1/model/AvroCollectionSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroEnumSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroFixedSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroJavaStringRepresentation.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroLogicalType.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroNamedSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroPrimitiveSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroRecordSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/AvroUnionSchema.java
- parser/src/main/java/com/linkedin/avroutil1/model/CodeLocation.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscIssues.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParseContext.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/LiteralOrIssue.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/Parsed.java
- parser/src/test/java/com/linkedin/avroutil1/parser/avsc/AvscParserTest.java
- parser/src/test/resources/schemas/TestRecordWithHorribleLogicalTypes.avsc
- parser/src/test/resources/schemas/TestRecordWithLogicalTypes.avsc
- parser/src/test/resources/schemas/TestRecordWithStringTypes.avsc
"negative" test cases will be in a follow-up PR
> parse logical types and string representation

- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDatumReaderWriterUtil.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastGenericDatumReader.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSerdeCache.java
- avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastSpecificDatumReader.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDatumReaderTest.java
- avro-fastserde/src/test/java/com/linkedin/avro/fastserde/FastDatumReaderWriterUtilTest.java
- get fast deserializers async
Original PR https://github.com/linkedin/avro-util/pull/243 was polluted with rebased commits.
> build and get fast deserializers async

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/tests/codegen-110/src/main/compat-avro/under110/RecordWithMultilineDoc.avsc
- helper/tests/codegen-110/src/main/raw-avro/by110/RecordWithMultilineDoc.avsc
- helper/tests/codegen-111/src/main/compat-avro/under111/RecordWithMultilineDoc.avsc
- helper/tests/codegen-111/src/main/raw-avro/by111/RecordWithMultilineDoc.avsc
- helper/tests/codegen-14/src/main/compat-avro/under14/RecordWithMultilineDoc.avsc
- helper/tests/codegen-15/src/main/compat-avro/under15/RecordWithMultilineDoc.avsc
- helper/tests/codegen-16/src/main/compat-avro/under16/RecordWithMultilineDoc.avsc
- helper/tests/codegen-16/src/main/raw-avro/by16/RecordWithMultilineDoc.avsc
- helper/tests/codegen-17/src/main/compat-avro/under17/RecordWithMultilineDoc.avsc
- helper/tests/codegen-17/src/main/raw-avro/by17/RecordWithMultilineDoc.avsc
- helper/tests/codegen-18/src/main/compat-avro/under18/RecordWithMultilineDoc.avsc
- helper/tests/codegen-18/src/main/raw-avro/by18/RecordWithMultilineDoc.avsc
- helper/tests/codegen-19/src/main/compat-avro/under19/RecordWithMultilineDoc.avsc
- helper/tests/codegen-19/src/main/raw-avro/by19/RecordWithMultilineDoc.avsc
- helper/tests/helper-tests-common/src/main/resources/RecordWithMultilineDoc.avsc
Also delete some unused code (made dead by #254).
> [helper] Add default values with escaped chars in tests.

- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/FieldBuilder111.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/FieldBuilder14.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/FieldBuilder15.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/FieldBuilder16.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/FieldBuilder17.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/FieldBuilder18.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/FieldBuilder19.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java
> [helper] Set the field default sort order to ASCENDING.

- avro-codegen/build.gradle
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGenerationConfig.java
- avro-codegen/src/test/java/com/linkedin/avro/codegen/testutil/CompilerHelper.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
- avro-codegen/src/test/resources/schemas/SimpleEnum.avsc
- parser/src/main/java/com/linkedin/avroutil1/model/AvroNamedSchema.java
> start of work on new specific class code generator

- spotbugs-plugin/src/main/java/com/linkedin/avroutil1/spotbugs/SchemaSerializationDetector.java
- spotbugs-plugin/src/main/resources/findbugs.xml
- spotbugs-plugin/src/main/resources/messages.xml
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/BadClass.java
- spotbugs-plugin/src/test/java/com/linkedin/avroutil1/spotbugs/SchemaSerializationDetectorTest.java
org.apache.avro.Schema.toString is vulnerable to AVRO-702 in avro v1.4
Added spotbugs to detect and notify
> Added spotbugs rule to detect usage of org.apache.avro.Schema.toString usage

- build.gradle
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaValidator.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110Adapter.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/Avro110SchemaValidator.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111Adapter.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/Avro111SchemaValidator.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14Adapter.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/Avro14SchemaValidator.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15Adapter.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/Avro15SchemaValidator.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16Adapter.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/Avro16SchemaValidator.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17Adapter.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/Avro17SchemaValidator.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18Adapter.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/Avro18SchemaValidator.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19Adapter.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/Avro19SchemaValidator.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelperDefaultsTest.java
- helper/tests/helper-tests-common/src/main/java/com/linkedin/avroutil1/UsefulBiConsumer.java
> validate type of numeric default values in AvroCompatibilityHelper.parse()

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/tests/helper-tests-110/src/test/java/com/linkedin/avroutil1/compatibility/avro110/AvroCompatibilityHelperAvro110Test.java
- helper/tests/helper-tests-111/src/test/java/com/linkedin/avroutil1/compatibility/avro111/AvroCompatibilityHelperAvro111Test.java
- helper/tests/helper-tests-14/src/test/java/com/linkedin/avroutil1/compatibility/avro14/AvroCompatibilityHelperAvro14Test.java
- helper/tests/helper-tests-15/src/test/java/com/linkedin/avroutil1/compatibility/avro15/AvroCompatibilityHelperAvro15Test.java
- helper/tests/helper-tests-16/src/test/java/com/linkedin/avroutil1/compatibility/avro16/AvroCompatibilityHelperAvro16Test.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/AvroCompatibilityHelperAvro17Test.java
- helper/tests/helper-tests-18/src/test/java/com/linkedin/avroutil1/compatibility/avro18/AvroCompatibilityHelperAvro18Test.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/AvroCompatibilityHelperAvro19Test.java
fixes https://github.com/linkedin/avro-util/issues/271
> adds detectAvroCompilerVersion() and accompanying tests

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/RandomRecordGenerator.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/RecordGenerationConfig.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/RecordGenerationContext.java
- helper/tests/codegen-14/src/main/compat-avro/under14/RecordWithSelfReference.avsc
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/RandomRecordGeneratorTest.java
> add RandomRecordGenerator handling for self-referencing schemas

- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroTypeAliasesTest.java
- helper/tests/helper-tests-allavro/src/test/resources/allavro/aliasesToNullNamespace/RecordInNullNamespace.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/aliasesToNullNamespace/RecordWithAliasesToNullNamespace.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/aliasesToNullNamespace/RecordWithDotlessAliases.avsc
- helper/tests/helper-tests-allavro/src/test/resources/allavro/aliasesToNullNamespace/RecordWithoutAliasesToNullNamespace.avsc
acts as documentation as well as demonstration
> demonstrate aliasing into the null namespace

- avro-builder/build.gradle
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/AvroSchemaBuilderUtils.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/ClasspathSchemaSet.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/DuplicateSchemaBehaviour.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/FileSystemSchemaSetProvider.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaHelper.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaId.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaSet.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaSetProvider.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SchemaVisitor.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SimpleSchemaSet.java
- avro-builder/src/main/java/com/linkedin/avroutil1/builder/SpecificCompilerHelper.java
- settings.gradle
Mostly a port of LinkedIn internal avro-schema-builder to be used in Venice where only used CLI options are --input/--output to generate class files.
> Add avro-builder module for building schema files 

- build.gradle
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
also dump jcenter for maven central in light of recent build issues
> make compiler detection more robust, also delay complaints about compiler to point-of-use

- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java
it looks like we were not properly handling the doc field for avro fields.
> support doc field for Avro Schema Fields

- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/resources/schemas/TestRecord.avsc
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/StringUtils.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroRecordUtil.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/RandomRecordGenerator.java
default representation of a string field can be set using the config for field and method's return value between String, Charsequence and Utf-8.
> String field and method representation by config

- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
`SchemaOrRef#getDecl()` doesn't handle resolved schemas via imports however since we want to support imports, we should use the `SchemaOrRef#getSchema()` method.
> [SpecificRecordClassGenerator] Change SchemaOrRef#getDecl() calls to SchemaOrRef#getSchema()

- avro-builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- helper/impls/helper-impl-14/build.gradle
- parser/src/main/java/com/linkedin/avroutil1/model/AvroMapSchema.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvroParseContext.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscFileParseContext.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParseResult.java
- parser/src/main/java/com/linkedin/avroutil1/writer/avsc/AvscSchemaWriter.java
- support for writing out default values for map and union fields
- print timings in code-gen op
> minor cleanups around code-gen

- avro-builder/tests/codegen-14/src/main/avro/vs14/ArrayOfStringRecord.avsc
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/ArrayOfStringRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
- avro-codegen/src/test/resources/schemas/ArrayOfStringRecord.avsc
Changes: 
AvroMissingFieldException  -> AvroRuntimeException for Min Avro support version < 1.9
readFieldOrderIfDiff -> readFieldOrder
> Updated avro Exception class and fieldOrder method compatible with 1.4

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/resources/schemas/DollarSignInDoc.avsc
- Handle $ literal in schema field names during codegen
> updated codegen to handle string literal in field names

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/resources/schemas/DollarSignInDoc.avsc
Handle Java poet literal sign in Field docs
> Handle Dollar literal for Java poet in fieldDocs

- avro-builder/tests/codegen-14/src/main/avro/vs14/MoneyRange.avsc
- avro-builder/tests/codegen-14/src/main/avro/vs14/RecordDefault.avsc
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/DefaultRecordTest.java
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/MoneyRangeTest.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
- avro-codegen/src/test/resources/schemas/MoneyRange.avsc
- avro-codegen/src/test/resources/schemas/RecordDefault.avsc
- parser/src/main/java/com/linkedin/avroutil1/parser/jsonpext/JsonObjectExtBuilder.java
- parser/src/main/java/com/linkedin/avroutil1/writer/avsc/AvscSchemaWriter.java
- Handles default value for Records in Avsc parsing.
- Added UTs for handling of Java Poet string literals in additional conditions in Codegen
> Specific record default

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/FieldBuilder.java
- helper/impls/helper-impl-110/src/main/java/com/linkedin/avroutil1/compatibility/avro110/FieldBuilder110.java
- helper/impls/helper-impl-111/src/main/java/com/linkedin/avroutil1/compatibility/avro111/FieldBuilder111.java
- helper/impls/helper-impl-14/src/main/java/com/linkedin/avroutil1/compatibility/avro14/FieldBuilder14.java
- helper/impls/helper-impl-15/src/main/java/com/linkedin/avroutil1/compatibility/avro15/FieldBuilder15.java
- helper/impls/helper-impl-16/src/main/java/com/linkedin/avroutil1/compatibility/avro16/FieldBuilder16.java
- helper/impls/helper-impl-17/src/main/java/com/linkedin/avroutil1/compatibility/avro17/FieldBuilder17.java
- helper/impls/helper-impl-18/src/main/java/com/linkedin/avroutil1/compatibility/avro18/FieldBuilder18.java
- helper/impls/helper-impl-19/src/main/java/com/linkedin/avroutil1/compatibility/avro19/FieldBuilder19.java
- helper/tests/helper-tests-110/src/test/java/com/linkedin/avroutil1/compatibility/avro110/Avro110FieldBuilderTest.java
- helper/tests/helper-tests-14/src/test/java/com/linkedin/avroutil1/compatibility/avro14/Avro14FieldBuilderTest.java
- helper/tests/helper-tests-15/src/test/java/com/linkedin/avroutil1/compatibility/avro15/Avro15FieldBuilderTest.java
- helper/tests/helper-tests-16/src/test/java/com/linkedin/avroutil1/compatibility/avro16/Avro16FieldBuilderTest.java
- helper/tests/helper-tests-17/src/test/java/com/linkedin/avroutil1/compatibility/avro17/Avro17FieldBuilderTest.java
- helper/tests/helper-tests-18/src/test/java/com/linkedin/avroutil1/compatibility/avro18/Avro18FieldBuilderTest.java
- helper/tests/helper-tests-19/src/test/java/com/linkedin/avroutil1/compatibility/avro19/Avro19FieldBuilderTest.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/FieldBuilderTest.java
fixes https://github.com/linkedin/avro-util/issues/383
> support setting field props in schema field builders

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/CodeTransformations.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/AvroCompatibilityHelper.java
- helper/tests/helper-tests-111/build.gradle
- helper/tests/helper-tests-111_0/README.md
- helper/tests/helper-tests-111_0/build.gradle
- helper/tests/helper-tests-111_0/src/test/java/com.linkedin.avroutil1.compatibility.avro111/AvroCompatibilityHelperAvro1110Test.java
- settings.gradle
Fixes #385.
Tested locally against Avro 1.11.1
> detectAvroVersion(): fixes 1.11.1 version handling

- avro-builder/tests/codegen-14/src/main/avro/vs14/FixedType.avsc
- avro-builder/tests/codegen-19/build.gradle
- avro-builder/tests/codegen-19/src/main/avro/vs19/FixedType.avsc
- avro-builder/tests/tests-allavro/build.gradle
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/FixedTypeTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- settings.gradle
Added more details to specific fixed generated via own codegen
> codegen added details for fixedgeneration

- avro-builder/tests/tests-allavro/build.gradle
- helper/helper-common/build.gradle
- helper/tests/helper-tests-allavro/build.gradle
fixes https://github.com/linkedin/avro-util/issues/401
> bump commons-text to 1.10.0

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/ListTransformer.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/MapTransformer.java
Followup on comments for PR 405
> update collection accessors

- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/AvroSchemaUtil.java
- helper/helper-common/src/main/java/com/linkedin/avroutil1/compatibility/SchemaResolutionResult.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/RecordGenerationConfig.java
- helper/tests/codegen-14/src/main/compat-avro-702-mitigated/under14/NewNewRecordWithAliases.avsc
- helper/tests/codegen-14/src/main/compat-avro-702-mitigated/under14/NewRecordWithAliases.avsc
- helper/tests/codegen-14/src/main/compat-avro-702-mitigated/under14/OldRecordWithoutAliases.avsc
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/AvroRecordUtilTest.java
"simple" (non-fullname) aliases TODO still
> implement alias support in generic to specific conversions

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
- primitive types (int, long, float, boolean, double) represented as primitives in generated code. 
- But, they will be represented by their respective classes (Integer, Long, Float, Boolean, Double) if part of a complex object like Union/Array/Map
> Codegen primitive type field handling

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/CodeGenOpConfig.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/tests/codegen-110/src/main/avro/vs110/BuilderTester.avsc
- avro-builder/tests/codegen-111/src/main/avro/vs111/BuilderTester.avsc
- avro-builder/tests/codegen-14/src/main/avro/vs14/BuilderTester.avsc
- avro-builder/tests/codegen-15/src/main/avro/vs15/BuilderTester.avsc
- avro-builder/tests/codegen-16/src/main/avro/vs16/BuilderTester.avsc
- avro-builder/tests/codegen-17/src/main/avro/vs17/BuilderTester.avsc
- avro-builder/tests/codegen-18/src/main/avro/vs18/BuilderTester.avsc
- avro-builder/tests/codegen-19/src/main/avro/vs19/BuilderTester.avsc
- avro-builder/tests/codegen-charseq-method/build.gradle
- avro-builder/tests/codegen-charseq-method/src/main/avro/charseqmethod/TestCollections.avsc
- avro-builder/tests/tests-allavro/build.gradle
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGenerationConfig.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
- avro-codegen/src/test/resources/schemas/BuilderTester.avsc
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/ListTransformer.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/collectiontransformer/MapTransformer.java
- settings.gradle
- Default String rep for method passed from SchemaBuilder to codegen
- Updated handling of default string type
- fixed bugs related to CharSeq method type
> Codegen string representation update

- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGeneratorUtil.java
- We don't need collection transformers for List[record]. So removing checking Record field checks.
> no check for Record fields in schemaContainsString check

- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscIssues.java
- parser/src/main/java/com/linkedin/avroutil1/parser/avsc/AvscParser.java
- parser/src/test/java/com/linkedin/avroutil1/parser/avsc/AvscParserTest.java
- parser/src/test/resources/schemas/BadRecordDefault.avsc
> check for missing field values in avro record literals

- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/SchemaBuilder.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/CodeGenOpConfig.java
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-builder/builder/src/test/java/com/linkedin/avroutil1/builder/SchemaBuilderTest.java
- avro-builder/tests/codegen-no-utf8-in-putbyindex/build.gradle
- avro-builder/tests/codegen-no-utf8-in-putbyindex/src/main/avro/charseqmethod/TestCollections.avsc
- avro-builder/tests/tests-allavro/build.gradle
- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordGenerationConfig.java
- settings.gradle
Config to control if utf8 encoding of string type fields ( + listOf/map) should be encoded to Utf8 during set in putByIndex
> Codegen: configurable encoding of String types to utf8 in putbyindex

- avro-builder/tests/tests-allavro/src/test/java/com/linkedin/avroutil1/builder/SpecificRecordTest.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
AllArg constructor in codegen will have all non-primitive types (boxed)
> Constructors to have non primitive types

- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
same thing as was done in https://github.com/linkedin/avro-util/pull/434
> apply avro-1.11 codegen fixes to our own codegen

- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- Builder classes don't assume fields with record types follow Builder pattern.
- doesn't produce 'fieldName'+builder field inside Builder class
- Sets value for such fields directly ( without using their builders)
Builder -> build() method moves from
```       if (minBuilder != null) {
try {
record.min = this.minBuilder.build();
}
catch (org.apache.avro.AvroRuntimeException e) {
com.linkedin.avroutil1.compatibility.exception.AvroUtilMissingFieldException avroUtilException = new com.linkedin.avroutil1.compatibility.exception.AvroUtilMissingFieldException(e);
avroUtilException.addParentField(record.getSchema().getField("min"));
throw avroUtilException;
}
}
else {
record.min = fieldSetFlags()[6] ? this.min : (vs111.Amount) com.linkedin.avroutil1.compatibility.AvroCompatibilityHelper.getSpeci …
```
> Codegen builder update : Stop assuming field type Records have builders

- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
- avro-codegen/src/test/resources/schemas/TestProblematicRecord.avsc
Just a missing `.getJsonValue()` call. added UTs
> [codegen] field with a union of map generates a `getSTRINGMap()` call

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/UtilsTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/Utils.java
- helper/helper-common/build.gradle
now i can finally build this project on my windows box
> fix fast-avro to pass tests on windows

- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/RandomRecordGenerator.java
- helper/helper/src/main/java/com/linkedin/avroutil1/compatibility/RecordGenerationContext.java
- helper/tests/helper-tests-allavro/src/test/java/com/linkedin/avroutil1/compatibility/RandomRecordGeneratorTest.java
- helper/tests/helper-tests-allavro/src/test/resources/allavro/RecursiveRecord.avsc
- parser/build.gradle
Recursive collections were throwing `StackOverflowError`s . This PR fixes that.
> handle recursive collections in RRG

- avro-builder/builder/build.gradle
- avro-builder/builder/src/main/java/com/linkedin/avroutil1/builder/operations/codegen/own/AvroUtilCodeGenOp.java
- avro-codegen/src/main/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGenerator.java
- avro-codegen/src/test/java/com/linkedin/avroutil1/codegen/SpecificRecordClassGeneratorTest.java
Avoid unnecessary JavaFile transforms
Parallelize avro java codegen
> Performance improvements

- avro-builder/builder-spi/build.gradle
- avro-builder/builder-spi/src/main/java/com/linkedin/avroutil1/builder/util/StreamUtil.java
- avro-builder/builder-spi/src/test/java/com/linkedin/avroutil1/builder/util/StreamUtilTest.java
Fix bugs with serial execution. Simplified version of #550
> Simplify and fix bugs in StreamUtil

- fastserde/avro-fastserde-tests-common/src/test/java/com/linkedin/avro/fastserde/FastGenericDeserializerGeneratorTest.java
- fastserde/avro-fastserde/src/main/java/com/linkedin/avro/fastserde/FastDeserializerGenerator.java
Missed a few cases in #576 when we have nested maps or array with the following cases:
1. In case we have a map<map<int>> inside a union, the old logic was passing a production which had the map-start,map-end symbols. However while processing maps our new map logic expects to see a map-end symbol as the action which we then check the production for to find the actions symbols for the map value. In this PR, we change union processing to seek to this action before passing to the map. Once again this indicates that we need a rewrite of this entire action processing logic to standardize which symbols are expected when we process any type to avoid unnecessary seeks and reduce confusion. 
2. If we have map<map<int>> on writer and map<union<map<int>> on reader there's actually no ambiguity about …
> Fix the map/array for nested maps/array with unions at play
